import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import sprouts from '@dicebear/styles/sprouts.json' with {type:'json'};

// Curate upstream vector components at authoring time. No avatar service, runtime
// generator, source SVG injection, animation stylesheet or expressions are shipped.
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const out=path.join(root,'browser-extension/extension/living/art');
const sourcePath=fileURLToPath(import.meta.resolve('@dicebear/styles/sprouts.json'));
const allowedTags=new Set(['g','path','circle','ellipse','rect','defs','clipPath']);
const allowedAttrs=new Set(['d','fill','stroke','stroke-width','stroke-linecap','stroke-linejoin','opacity','transform','clip-path','id','fill-rule','cx','cy','r','rx','ry','x','y','width','height']);
const palette={plant:'var(--nook-leaf)',pot:'var(--nook-pot)',ink:'#243a38',bloom:'#d4a492'};
const picks=[{id:'window-palm',plant:'palm',pot:'cylinder'},{id:'desk-sprout',plant:'sprout',pot:'bowl'}];
function compile(node,prefix){
 if(node.type!=='element'||!allowedTags.has(node.name))throw new Error('Unexpected upstream SVG element: '+node.name);
 const attrs={};
 for(const[key,raw]of Object.entries(node.attributes||{})){
  if(!allowedAttrs.has(key))throw new Error('Unexpected upstream SVG attribute: '+key);
  let value=typeof raw==='object'&&raw?.type==='color'?palette[raw.name]:raw;
  if(typeof value!=='string')throw new Error('Unresolved upstream SVG attribute: '+key);
  if(key==='id')value=prefix+'-'+value;
  value=value.replace(/url\(#([^)]*)\)/g,(_,id)=>`url(#${prefix}-${id})`);
  if(/(?:https?:|javascript:|data:|[<>])/.test(value))throw new Error('External or executable SVG data');
  attrs[key]=value;
 }
 return [node.name,attrs,(node.children||[]).map(child=>compile(child,prefix))];
}
const art=Object.fromEntries(picks.map(pick=>[pick.id,[
 ['g',{transform:'translate(17 9)'},sprouts.components.plant.variants[pick.plant].elements.map(node=>compile(node,'cd-'+pick.id))],
 ['g',{transform:'translate(17 58)'},sprouts.components.pot.variants[pick.pot].elements.map(node=>compile(node,'cd-'+pick.id))]
]]));
if(sprouts.meta.license.name!=='CC0 1.0')throw new Error('Upstream artwork license changed; review before regenerating.');
const generated='// Generated by tools/artwork/generate.mjs from @dicebear/styles 10.6.0.\n// Sprouts by DiceBear, CC0 1.0. See art-sources.json and ARTWORK-LICENSE.txt beside this file.\nexport const TOKYO_PLANT_ART='+JSON.stringify(art)+';\n';
fs.writeFileSync(path.join(out,'tokyo-plant-art.mjs'),generated);
fs.writeFileSync(path.join(out,'art-sources.json'),JSON.stringify({
 schemaVersion:1,collection:'Tokyo planted reading nook',
 package:'@dicebear/styles',version:'10.6.0',
 repository:'https://github.com/dicebear/styles',
 source:'https://www.dicebear.com/styles/sprouts/',
 definition:sprouts.$id,
 definitionSha256:crypto.createHash('sha256').update(fs.readFileSync(sourcePath)).digest('hex'),
 creator:sprouts.meta.creator,license:sprouts.meta.license,
 selections:picks,
 changes:['Selected plant and pot components only; omitted avatar face, background and animation.','Mapped green and terracotta colors to the Tokyo day/dusk/night palette.','Prefixed every SVG ID/reference to avoid collisions.','Composed the two props in the existing Tokyo world with the original ChatDrobe cat rig.'],
 output:'tokyo-plant-art.mjs',outputSha256:crypto.createHash('sha256').update(generated).digest('hex')
},null,2)+'\n');
console.log('Generated Tokyo plant artwork and provenance from DiceBear styles 10.6.0.');
