import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import sprouts from '@dicebear/styles/sprouts.json' with {type:'json'};
import landscape from '@dicebear/styles/landscape.json' with {type:'json'};
import planets from '@dicebear/styles/planets.json' with {type:'json'};

// Curate upstream vector components at authoring time. No avatar service, runtime
// generator, source SVG injection, animation stylesheet or expressions are shipped.
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const out=path.join(root,'browser-extension/extension/living/art');
const sourcePath=fileURLToPath(import.meta.resolve('@dicebear/styles/sprouts.json'));
const allowedTags=new Set(['g','path','circle','ellipse','rect','defs','clipPath','radialGradient','stop']);
const allowedAttrs=new Set(['d','fill','stroke','stroke-width','stroke-linecap','stroke-linejoin','opacity','transform','clip-path','id','fill-rule','cx','cy','r','rx','ry','x','y','width','height','fill-opacity','stroke-opacity','gradientUnits','offset','stop-color','stop-opacity']);
const palette={plant:'var(--nook-leaf)',pot:'var(--nook-pot)',ink:'#243a38',bloom:'#d4a492'};
const picks=[{id:'window-palm',plant:'palm',pot:'cylinder'},{id:'desk-sprout',plant:'sprout',pot:'bowl'}];
function compile(node,prefix,colors=palette){
 if(node.type!=='element'||!allowedTags.has(node.name))throw new Error('Unexpected upstream SVG element: '+node.name);
 const attrs={};
 for(const[key,raw]of Object.entries(node.attributes||{})){
  // This one upstream marker only scopes its omitted animation stylesheet.
  if(key==='class'&&raw==='dbpa-surface')continue;
  if(!allowedAttrs.has(key))throw new Error('Unexpected upstream SVG attribute: '+key);
  let value=typeof raw==='object'&&raw?.type==='color'?colors[raw.name]:raw;
  if(typeof value!=='string')throw new Error('Unresolved upstream SVG attribute: '+key);
  if(key==='id')value=prefix+'-'+value;
  value=value.replace(/url\(#([^)]*)\)/g,(_,id)=>`url(#${prefix}-${id})`);
  if(/(?:https?:|javascript:|data:|[<>])/.test(value))throw new Error('External or executable SVG data');
  attrs[key]=value;
 }
 return [node.name,attrs,(node.children||[]).map(child=>compile(child,prefix,colors))];
}
const art=Object.fromEntries(picks.map(pick=>[pick.id,[
 ['g',{transform:'translate(17 9)'},sprouts.components.plant.variants[pick.plant].elements.map(node=>compile(node,'cd-'+pick.id))],
 ['g',{transform:'translate(17 58)'},sprouts.components.pot.variants[pick.pot].elements.map(node=>compile(node,'cd-'+pick.id))]
]]));
if(sprouts.meta.license.name!=='CC0 1.0')throw new Error('Upstream artwork license changed; review before regenerating.');
const generated='// Generated by tools/artwork/generate.mjs from @dicebear/styles 10.6.0.\n// Sprouts by DiceBear, CC0 1.0. See art-sources.json and ARTWORK-LICENSE.txt beside this file.\nexport const TOKYO_PLANT_ART='+JSON.stringify(art)+';\n';
fs.writeFileSync(path.join(out,'tokyo-plant-art.mjs'),generated);
fs.writeFileSync(path.join(out,'art-sources.json'),JSON.stringify({
 schemaVersion:1,collection:'Tokyo planted reading nook',
 package:'@dicebear/styles',version:'10.6.0',
 repository:'https://github.com/dicebear/styles',
 source:'https://www.dicebear.com/styles/sprouts/',
 definition:sprouts.$id,
 definitionSha256:crypto.createHash('sha256').update(fs.readFileSync(sourcePath)).digest('hex'),
 creator:sprouts.meta.creator,license:sprouts.meta.license,
 selections:picks,
 changes:['Selected plant and pot components only; omitted avatar face, background and animation.','Mapped green and terracotta colors to the Tokyo day/dusk/night palette.','Prefixed every SVG ID/reference to avoid collisions.','Composed the two props in the existing Tokyo world with the original ChatDrobe cat rig.'],
 output:'tokyo-plant-art.mjs',outputSha256:crypto.createHash('sha256').update(generated).digest('hex')
},null,2)+'\n');
// These collections are already included in the same locked authoring package.
// Select components, never the upstream randomized canvas or animation component.
const worldSelections=[
 {id:'train',style:'landscape',definition:landscape,palette:{hill1:'var(--far)',hill2:'var(--grass)',hill3:'var(--field)'},picks:[
  {id:'distant-ridge',component:'hill1',variant:'ridge'},
  {id:'rolling-fields',component:'hill2',variant:'rolling'},
  {id:'near-meadow',component:'hill3',variant:'gentle'}]},
 {id:'starship',style:'planets',definition:planets,palette:{},picks:[
  {id:'earth-surface',component:'surface',variant:'terra'},
  {id:'moon-surface',component:'surface',variant:'cratered'},
  {id:'jupiter-surface',component:'surface',variant:'banded'},
  {id:'planet-shade',component:'shade',variant:'soft'}]}
];
const worlds={};
for(const selection of worldSelections){
 if(selection.definition.meta.license.name!=='CC0 1.0')throw new Error('Upstream artwork license changed; review '+selection.style);
 worlds[selection.id]=Object.fromEntries(selection.picks.map(pick=>[pick.id,selection.definition.components[pick.component].variants[pick.variant].elements.map(node=>compile(node,'cd-'+selection.id+'-'+pick.id,selection.palette))]));
}
const worldOutput='// Generated by tools/artwork/generate.mjs from @dicebear/styles 10.6.0.\n// Landscape and Planets by DiceBear, CC0 1.0. See world-art-sources.json and ARTWORK-LICENSE.txt.\nexport const WORLD_ART='+JSON.stringify(worlds)+';\n';
fs.writeFileSync(path.join(out,'world-art.mjs'),worldOutput);
fs.writeFileSync(path.join(out,'world-art-sources.json'),JSON.stringify({
 schemaVersion:1,package:'@dicebear/styles',version:'10.6.0',repository:'https://github.com/dicebear/styles',
 collections:worldSelections.map(selection=>({
  world:selection.id,style:selection.style,source:'https://www.dicebear.com/styles/'+selection.style+'/',
  definition:selection.definition.$id,
  definitionSha256:crypto.createHash('sha256').update(fs.readFileSync(fileURLToPath(import.meta.resolve('@dicebear/styles/'+selection.style+'.json')))).digest('hex'),
  creator:selection.definition.meta.creator,license:selection.definition.meta.license,selections:selection.picks,
  changes:selection.id==='train'?[
   'Selected three static hill contours; omitted upstream randomness, orb, background and animation.',
   'Mapped hill colors to existing Train journey and day/dusk/night palette variables.',
   'Placed contours behind existing carriage, trees and cottage; retained mountain and city stages.'
  ]:[
   'Selected terra, cratered and banded surfaces and soft shading; omitted stars, rings, moons, randomness and animation.',
   'Removed the dbpa-surface CSS marker; the original ChatDrobe scheduler controls motion.',
   'Prefixed every SVG ID/reference and fitted surfaces to the existing planet disc.',
   'Display Earth, Moon and Jupiter surfaces only in their matching journey stages; retain asteroid and deep-space stages.'
  ]
 })),output:'world-art.mjs',outputSha256:crypto.createHash('sha256').update(worldOutput).digest('hex')
},null,2)+'\n');
console.log('Generated Tokyo, Train and Starship artwork and provenance from DiceBear styles 10.6.0.');
