import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {randomUUID,createHmac} from 'node:crypto';
import {connectStore} from '../pg-store.mjs';import {migrateDatabase} from '../database-migrations.mjs';import {migrateAccounts} from '../accounts-migrate.mjs';import {migrateAccess} from '../access-migrate.mjs';
import {accountsStore} from '../accounts-store.mjs';import {accountService} from '../accounts-service.mjs';import {accountPayments,REQUIRED_EVENTS} from '../accounts-payments.mjs';import {webConfig,hash,secret,COOKIE,CHALLENGE_COOKIE,cookieValue,requireOrigin} from '../accounts-policy.mjs';
import {ownerAccess} from '../owner-access.mjs';import {makeOwnerHash,ownerConfiguration} from '../owner-credentials.mjs';import {extensionDevices} from '../extension-devices.mjs';import {createExtensionHandler} from '../extension-http.mjs';import {createAccountHandler} from '../accounts-http.mjs';import {createHandler} from '../http.mjs';
import {testConfig,fakeStripe} from '../tests/fakes.mjs';import {API_VERSION} from '../security.mjs';import verifier from '../../contracts/extension-entitlement.cjs';
import {membership} from '../premium-membership.mjs';
if(!process.env.BILLING_DATABASE_URL)throw Error('An isolated PostgreSQL URL is required.');
async function db(t){const u=new URL(process.env.BILLING_DATABASE_URL);if(!['127.0.0.1','localhost'].includes(u.hostname))throw Error('Disposable local PostgreSQL only.');const admin=await connectStore(u.href),name='cd_access_'+randomUUID().replaceAll('-','');await admin.pool.query(`CREATE DATABASE ${name}`);u.pathname='/'+name;const result=await connectStore(u.href);t.after(async()=>{await result.pool.end();await admin.pool.query(`DROP DATABASE ${name} WITH (FORCE)`);await admin.pool.end();});return {...result,url:u.href};}
test('real HTTP and PostgreSQL: complimentary admin plus ordinary-customer payment/recovery stay separate',async t=>{
 const{pool,store,url}=await db(t);await migrateDatabase(pool);await migrateAccounts(pool);const migrations=await Promise.all([migrateAccess(pool),migrateAccess(pool)]);assert.equal(migrations.filter(x=>x.applied).length,1);
 const password='fixture-only-long-owner-password-123!',owner=ownerConfiguration({ADMIN_EMAIL:'owner@example.test',ADMIN_PASSWORD_HASH:await makeOwnerHash(password)});await pool.query('INSERT INTO public.chatdrobe_admin_invites(email_hash) VALUES($1)',[hash(owner.email)]);
 const web={...webConfig({}),ownerReady:true,emailReady:true},original=accountsStore(pool),ownerLogin=ownerAccess({pool,store,accounts:original,configuration:owner}),accounts={...original,session:ownerLogin.authenticateSession};
 const cfg=testConfig(),provider=fakeStripe(),env={DATABASE_URL:url,BILLING_MODE:'test',BILLING_ORIGIN:web.origin,STRIPE_SECRET_KEY:cfg.stripeSecret,STRIPE_WEBHOOK_SECRET:cfg.webhookSecret,STRIPE_PLUS_PRICE_ID:cfg.priceId,BILLING_SIGNING_PRIVATE_KEY:cfg.privateKey.export({format:'pem',type:'pkcs8'}),STRIPE_WEBHOOK_ENDPOINT_ID:'we_fixture'};
 const portal={id:'bpc_fixture',object:'billing_portal.configuration',active:true,is_default:true,livemode:false,features:{subscription_cancel:{enabled:true,mode:'at_period_end'},payment_method_update:{enabled:true},invoice_history:{enabled:true},subscription_update:{enabled:false}}};provider.data.set('/billing_portal/configurations',{object:'list',data:[portal],has_more:false,url:'/v1/billing_portal/configurations'});provider.data.set('/webhook_endpoints/we_fixture',{id:'we_fixture',livemode:false,status:'enabled',url:web.origin+'/api/billing?action=webhook',api_version:API_VERSION,enabled_events:REQUIRED_EVENTS});
 const sent=[],payments=accountPayments({env,web,accounts,store,providerFactory:()=>provider.stripe}),base=accountService({accounts,billingStore:store,config:web,payments,mailer:async v=>sent.push(v)}),devices=extensionDevices({pool,store,owner});
 const service={...base,ownerLogin:ownerLogin.login},rt={pool,store,web,owner,accounts,payments,devices,service,accessSigningConfiguration:()=>cfg};
 const accountHandler=createAccountHandler(async()=>rt,{config:()=>web,owner:()=>owner}),extensionHandler=createExtensionHandler(async()=>rt),billingHandler=createHandler(()=>payments.dependencies(),{authenticate:async req=>{requireOrigin(req,web);return (await service.authenticate(cookieValue(req.headers.cookie,COOKIE))).billingId;},checkoutGuard:()=>payments.requireCheckout(),billingStatus:()=>payments.status()});
 const server=http.createServer((req,res)=>req.url.startsWith('/api/account')?accountHandler(req,res):req.url.startsWith('/api/extension')?extensionHandler(req,res):billingHandler(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const origin='http://127.0.0.1:'+server.address().port;let cookie='';
 const post=(family,action,body={},headers={})=>fetch(origin+'/api/'+family+'?action='+action,{method:'POST',headers:{origin:web.origin,'Content-Type':'application/json','X-ChatDrobe-Request':'account-v1',cookie,...headers},body:JSON.stringify(body)});
 const ext=(action,credential,input={})=>post('extension',action,input,{origin:'chrome-extension://'+'a'.repeat(32),authorization:'Bearer '+credential,cookie:''});
 const takeCookie=(r,name=COOKIE)=>r.headers.getSetCookie().find(c=>c.startsWith(name+'=')).split(';')[0];
 async function pair(credential){const r=await ext('start',credential,{extensionId:'a'.repeat(32)});assert.equal(r.status,200);const link=await r.json();assert.ok(!link.verificationUrl.includes(credential));assert.equal((await post('account','link-extension',{code:link.code,confirmed:false})).status,400);assert.equal((await post('account','link-extension',{code:link.code,confirmed:true})).status,200);assert.equal((await post('account','link-extension',{code:link.code,confirmed:true})).status,409);return link;}
 let response=await post('account','owner-login',{email:owner.email,password:'wrong-password'});assert.equal(response.status,401);response=await post('account','owner-login',{email:owner.email,password,role:'admin'});assert.equal(response.status,400);
 response=await post('account','owner-login',{email:owner.email,password});assert.equal(response.status,200);assert.match(response.headers.getSetCookie()[0],/Max-Age=2592000/);cookie=takeCookie(response);const ownerCookie=cookie,admin=await service.authenticate(cookie.split('=')[1]);assert.equal(admin.role,'admin');assert.equal(sent.length,0);
 const ownerCredential=secret();await pair(ownerCredential);let access=await ext('entitlement',ownerCredential).then(r=>r.json());assert.equal(access.plan,'plus');assert.equal(access.accessSource,'admin');assert.equal(provider.calls.length,0);assert.equal((await verifier.verify(access.token,{...cfg,deviceId:hash(ownerCredential)})).adminPremium,true);assert.equal((await service.profile(admin)).subscription.plan,'free');assert.equal(membership(admin,{plan:'free'}).complimentary,true);
 // Thirty-day remembered owner session does not mean privileged operations stay fresh.
 assert.ok(await ownerLogin.authenticateSession(hash(cookie.split('=')[1]),Math.floor(Date.now()/1000)+86400));assert.equal(await ownerLogin.authenticateSession(hash(cookie.split('=')[1]),Math.floor(Date.now()/1000)+31*86400),null);
 assert.equal((await post('account','admin-activate',{enabled:true})).status,200);
 async function signInMember(mode){const r=await post('account','request-code',{email:'member@example.test',mode,acceptBeta:true});assert.equal(r.status,202);const challenge=takeCookie(r,CHALLENGE_COOKIE),v=await post('account','verify-code',{code:sent.at(-1).code},{cookie:challenge});assert.equal(v.status,200);assert.match(v.headers.getSetCookie()[0],/Max-Age=2592000/);cookie=takeCookie(v);return service.authenticate(cookie.split('=')[1]);}
 const member=await signInMember('signup');assert.equal(member.role,'user');assert.equal((await post('account','admin-activate',{enabled:true})).status,403);
 const credential=secret();await pair(credential);access=await ext('entitlement',credential).then(r=>r.json());assert.equal(access.plan,'free');assert.equal((await post('billing','checkout',{world:'starlit'})).status,200);
 const saved=await store.read(member.billingId),sub=provider.pay(saved.sessionId,Math.floor(Date.now()/1000));const event={id:'evt_'+randomUUID().replaceAll('-',''),livemode:false,api_version:API_VERSION,type:'checkout.session.completed',data:{object:{id:saved.sessionId}}},raw=JSON.stringify(event),stamp=Math.floor(Date.now()/1000),sig=createHmac('sha256',cfg.webhookSecret).update(stamp+'.'+raw).digest('hex');
 response=await fetch(origin+'/api/billing?action=webhook',{method:'POST',headers:{'Content-Type':'application/json','stripe-signature':`t=${stamp},v1=${sig}`},body:raw});assert.equal(response.status,200);
 const verifyConfig={...cfg,deviceId:hash(credential)};access=await ext('entitlement',credential).then(r=>r.json());const proof=await verifier.verify(access.token,verifyConfig);assert.equal(proof.premium,true);assert.equal(proof.testSubscription,true);assert.equal(proof.adminPremium,false);assert.equal((await service.profile(member)).subscription.plan,'test_plus');assert.equal((await post('billing','portal')).status,200);
 const canonical=provider.data.get('/subscriptions/'+sub.id);canonical.cancel_at_period_end=true;access=await ext('entitlement',credential).then(r=>r.json());assert.equal(access.plan,'plus');assert.equal(access.cancelAtPeriodEnd,true);
 const oldCookie=cookie,recovered=await signInMember('signin');assert.notEqual(cookie,oldCookie);assert.equal(recovered.billingId,member.billingId);const second=secret();await pair(second);const secondAccess=await ext('entitlement',second).then(r=>r.json());assert.equal((await verifier.verify(secondAccess.token,{...cfg,deviceId:hash(second)})).premium,true);await assert.rejects(verifier.verify(secondAccess.token,verifyConfig));
 assert.equal((await post('account','revoke-device',{deviceId:hash(credential)})).status,200);assert.equal((await ext('entitlement',credential)).status,401);canonical.status='canceled';access=await ext('entitlement',second).then(r=>r.json());assert.equal((await verifier.verify(access.token,{...cfg,deviceId:hash(second)})).premium,false);
 // Admin demotion is observed from the current DB row, without recreating the device.
 await pool.query("UPDATE public.chatdrobe_accounts SET role='user' WHERE id=$1",[admin.id]);access=await ext('entitlement',ownerCredential).then(r=>r.json());assert.equal(access.plan,'free');await assert.rejects(ownerLogin.login({email:owner.email,password},'demotion-test'),{code:'OWNER_REVIEW_REQUIRED'});
 const rotated=ownerConfiguration({ADMIN_EMAIL:owner.email,ADMIN_PASSWORD_HASH:await makeOwnerHash(password+'-rotated')}),newOwner=ownerAccess({pool,store,accounts:original,configuration:rotated});assert.equal(await newOwner.authenticateSession(hash(ownerCookie.split('=')[1]),Math.floor(Date.now()/1000)),null);await assert.rejects(extensionDevices({pool,store,owner:rotated}).device(hash(ownerCredential)),{code:'DEVICE_SIGN_IN_REQUIRED'});
 assert.equal((await ext('entitlement',secret())).status,401);const expired=secret(),pending=await ext('start',expired,{extensionId:'a'.repeat(32)}).then(r=>r.json());await pool.query("UPDATE public.chatdrobe_extension_devices SET expires_at=now()-interval '1 minute' WHERE credential_hash=$1",[hash(expired)]);await assert.rejects(devices.approve(member,pending.code),{code:'LINK_EXPIRED'});assert.equal((await ext('start',credential,{extensionId:'a'.repeat(32)})).status,409);
});
