import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {connectStore} from '../pg-store.mjs';import {migrateDatabase} from '../database-migrations.mjs';import {migrateAccounts} from '../accounts-migrate.mjs';import {accountSchemaReady} from '../accounts-schema.mjs';import {accountsStore} from '../accounts-store.mjs';import {accountService} from '../accounts-service.mjs';import {accountPayments,REQUIRED_EVENTS} from '../accounts-payments.mjs';import {webConfig,hash,secret,requireAdmin} from '../accounts-policy.mjs';import {API_VERSION} from '../security.mjs';import {testConfig,fakeStripe} from '../tests/fakes.mjs';
if(!process.env.BILLING_DATABASE_URL)throw new Error('Use an isolated PostgreSQL database for account tests.');
async function isolated(t){const u=new URL(process.env.BILLING_DATABASE_URL);if(!['localhost','127.0.0.1'].includes(u.hostname))throw new Error('Account migration tests require a disposable localhost PostgreSQL instance.');const admin=await connectStore(u.href),name='cd_accounts_'+randomUUID().replaceAll('-','');await admin.pool.query(`CREATE DATABASE ${name}`);u.pathname='/'+name;const c=await connectStore(u.href);t.after(async()=>{await c.pool.end();await admin.pool.query(`DROP DATABASE ${name} WITH (FORCE)`);await admin.pool.end();});return {...c,url:u.href};}
test('PostgreSQL: OTP ownership, admin claim, recovery, test payments and revocation',async t=>{
 const{pool,store,url}=await isolated(t);await migrateDatabase(pool);const migrations=await Promise.all([migrateAccounts(pool),migrateAccounts(pool)]);assert.equal(migrations.filter(x=>x.applied).length,1);assert.equal(await accountSchemaReady(pool),true);
 const initial=await pool.query("SELECT claimed_by FROM public.chatdrobe_admin_invites WHERE email_hash='43e81ed44741dc161c7b2e754de83c23410f6b13c345a40ef737b16b68aaa983'");assert.equal(initial.rowCount,1);assert.equal(initial.rows[0].claimed_by,null);
 const accounts=accountsStore(pool),web=webConfig({RESEND_API_KEY:'re_'+'fixture'.repeat(5),AUTH_EMAIL_FROM:'ChatDrobe <login@chatdrobe.com>'}),cfg=testConfig(),provider=fakeStripe(),now=Math.floor(Date.now()/1000);
 const env={DATABASE_URL:url,BILLING_MODE:'test',BILLING_ORIGIN:web.origin,STRIPE_SECRET_KEY:cfg.stripeSecret,STRIPE_WEBHOOK_SECRET:cfg.webhookSecret,STRIPE_PLUS_PRICE_ID:cfg.priceId,BILLING_SIGNING_PRIVATE_KEY:cfg.privateKey.export({format:'pem',type:'pkcs8'}),STRIPE_WEBHOOK_ENDPOINT_ID:'we_fixture'};
 provider.data.set('/webhook_endpoints/we_fixture',{id:'we_fixture',livemode:false,status:'enabled',url:web.origin+'/api/billing?action=webhook',api_version:API_VERSION,enabled_events:REQUIRED_EVENTS});provider.data.set('/billing_portal/configurations',{object:'list',has_more:false,data:[{id:'bpc_fixture',object:'billing_portal.configuration',is_default:true,livemode:false,active:true,features:{subscription_cancel:{enabled:true,mode:'at_period_end'},payment_method_update:{enabled:true},invoice_history:{enabled:true},subscription_update:{enabled:false}}}]});
 const payments=accountPayments({env,web,accounts,store,providerFactory:()=>provider.stripe}),sent=[],service=accountService({accounts,billingStore:store,config:web,payments,mailer:async v=>sent.push(v),now:()=>now});
 const suffix=randomUUID().replaceAll('-',''),email='tester-'+suffix+'@example.test',owner='owner-'+suffix+'@example.test';await pool.query('INSERT INTO public.chatdrobe_admin_invites(email_hash) VALUES($1)',[hash(owner)]);
 async function request(address,mode='signup'){const r=await service.requestCode({email:address,mode,acceptBeta:true},{ip:secret()});return {...r,code:sent.at(-1).code};}
 async function login(address,mode='signup'){const c=await request(address,mode),v=await service.verifyCode(c.nonce,c.code,{ip:secret()});return {challenge:c,...v,user:await service.authenticate(v.token)};}
 const first=await request(email);assert.equal((await pool.query('SELECT id FROM public.chatdrobe_accounts WHERE email=$1',[email])).rowCount,0);
 for(let i=0;i<5;i++)await assert.rejects(service.verifyCode(first.nonce,first.code==='00000000'?'99999999':'00000000',{ip:secret()}),{code:'CODE_INVALID'});await assert.rejects(service.verifyCode(first.nonce,first.code,{ip:secret()}),{code:'CODE_INVALID'});
 const member=await login(email);assert.equal(member.user.role,'user');assert.equal(member.user.verifiedAt instanceof Date,true);await assert.rejects(service.verifyCode(member.challenge.nonce,member.challenge.code,{ip:secret()}),{code:'CODE_INVALID'});await assert.rejects(service.admin(member.user,{}),{code:'FORBIDDEN'});await assert.rejects(service.activate(member.user,true),{code:'FORBIDDEN'});
 const admin=await login(owner);assert.equal(admin.user.role,'admin');requireAdmin(admin.user);assert.equal((await pool.query('SELECT claimed_by FROM public.chatdrobe_admin_invites WHERE email_hash=$1',[hash(owner)])).rows[0].claimed_by,admin.user.id);
 assert.equal((await payments.status()).enabled,false);await assert.rejects(payments.requireCheckout(),{code:'BILLING_DISABLED'});await assert.rejects(service.activate({...admin.user,authenticatedAt:now-1000},true),{code:'REAUTHENTICATE'});
 const{service:billing}=await payments.dependencies(),before=await service.admin(admin.user,{q:suffix});assert.equal(before.total,2);assert.equal(before.counts.paid_live,0);
 await service.activate(admin.user,true);assert.equal((await payments.status()).enabled,true);await payments.requireCheckout();await billing.checkout(member.user.billingId,'starlit');const saved=await store.read(member.user.billingId),sub=provider.pay(saved.sessionId,now);assert.equal((await billing.refresh(member.user.billingId)).plan,'plus');
 const plus=await service.admin(admin.user,{q:suffix,plan:'test_plus'});assert.equal(plus.total,1);assert.equal(plus.users[0].email,email);assert.equal(plus.counts.paid_live,0);
 const recovered=await login(email,'signin');assert.notEqual(recovered.token,member.token);assert.equal(recovered.user.id,member.user.id);assert.equal(recovered.user.billingId,member.user.billingId);assert.equal((await service.profile(recovered.user)).subscription.plan,'test_plus');
 assert.equal(provider.calls.find(x=>x.path==='/checkout/sessions').options.values.success_url,web.origin+'/account/?checkout=returned');await billing.portal(member.user.billingId);assert.equal(provider.calls.find(x=>x.path==='/billing_portal/sessions').options.values.configuration,'bpc_fixture');
 assert.deepEqual(provider.calls.find(x=>x.path==='/billing_portal/configurations').options.values,{active:true,is_default:true,limit:2});
 await service.activate(admin.user,false);await assert.rejects(payments.requireCheckout(),{code:'BILLING_DISABLED'});provider.data.get('/subscriptions/'+sub.id).status='canceled';const paused=await payments.dependencies();assert.equal(paused.config.enabled,true);await paused.service.webhook({id:'evt_'+suffix,type:'customer.subscription.updated',livemode:false,api_version:API_VERSION,data:{object:{id:sub.id}}});assert.equal((await billing.refresh(member.user.billingId)).plan,'free');
 assert.equal((await service.admin(admin.user,{q:"' OR true --"})).total,0);await service.signoutAll(member.user);await assert.rejects(service.authenticate(member.token),{code:'SIGN_IN_REQUIRED'});await assert.rejects(service.authenticate(recovered.token),{code:'SIGN_IN_REQUIRED'});
 await pool.query("UPDATE public.chatdrobe_accounts SET role='user' WHERE id=$1",[admin.user.id]);const demoted=await login(owner,'signin');assert.equal(demoted.user.role,'user');await assert.rejects(service.setup(demoted.user),{code:'FORBIDDEN'});
 const unknown=await request('unknown-'+suffix+'@example.test','signin');await assert.rejects(service.verifyCode(unknown.nonce,unknown.code,{ip:secret()}),{code:'SIGNUP_REQUIRED'});
 const tokens=await pool.query('SELECT token_hash FROM public.chatdrobe_sessions WHERE account_id=$1',[admin.user.id]);assert.ok(tokens.rows.every(r=>r.token_hash!==admin.token&&/^[a-f0-9]{64}$/.test(r.token_hash)));const exposed=await pool.query('SELECT count(*)::int AS count FROM pg_class c CROSS JOIN LATERAL aclexplode(c.relacl) a WHERE c.relname=ANY($1::text[]) AND a.grantee=0',[['chatdrobe_accounts','chatdrobe_sessions','chatdrobe_admin_invites']]);assert.equal(exposed.rows[0].count,0);assert.ok((await pool.query('SELECT count(*)::int AS n FROM public.chatdrobe_account_audit WHERE actor=$1',[admin.user.id])).rows[0].n>0);
});
