/** Deterministically adapt the pinned, expression-free SVG light runtime to a local module.
 * Usage: npm pack lottie-web@5.13.0 --ignore-scripts; extract outside the repository;
 * node browser-extension/scripts/vendor-lottie.mjs /path/to/extracted/package
 * This script never fetches code and rejects a different upstream source or license.
 */
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';

export const UPSTREAM_SHA256='96b0710aa725b09ecab886afad23deb073b65436eabcfde225e0b3781567222b';
export const LICENSE_SHA256='9d8d4d8b4bb99572ee8b51025a30b8493d949798cac465c6c15b1b29420bcb06';
const hash=value=>createHash('sha256').update(value).digest('hex');
export function adaptLottie(source){
 if(hash(source)!==UPSTREAM_SHA256)throw new Error('Unreviewed Lottie source; expected lottie-web@5.13.0 SVG light.');
 const marker="})(this, (function () { 'use strict';";
 const start=source.indexOf(marker),end=source.lastIndexOf('\n}));');
 if(start<0||end<start)throw new Error('Unexpected upstream module wrapper.');
 let body=source.slice(start+marker.length,end);
 // Our only entry point is loadAnimation with reviewed in-memory shape data. Never
 // inspect host-page scripts/data-animation elements or publish page-wide globals.
 body=body.replace("var standalone = '__[STANDALONE]__';",'var standalone = false;');
 const scanStart=body.indexOf('  function checkReady() {'),scanEnd=body.indexOf('  var ShapeModifiers = function () {',scanStart);
 if(scanStart<0||scanEnd<scanStart)throw new Error('Unexpected upstream automatic discovery block.');
 body=body.slice(0,scanStart)+body.slice(scanEnd);
 const result='/* lottie-web 5.13.0, MIT, Copyright (c) 2015 Bodymovin. See lottie-LICENSE.txt.\n * Generated by scripts/vendor-lottie.mjs: ESM export; no DOM auto-discovery or globals. */\nconst lottie = (function () {\n'+body+'\n})();\nexport default lottie;\n';
 if(/\beval\s*\(|\bnew\s+Function\s*\(/.test(result))throw new Error('Executable expressions are not permitted.');
 return result;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const input=process.argv[2];if(!input)throw new Error('Provide the extracted lottie-web@5.13.0 package directory.');
 const license=fs.readFileSync(path.join(input,'LICENSE.md'));
 if(hash(license)!==LICENSE_SHA256)throw new Error('Unexpected upstream MIT license.');
 const output=adaptLottie(fs.readFileSync(path.join(input,'build/player/lottie_light.js'),'utf8'));
 const target=fileURLToPath(new URL('../extension/living/vendor/',import.meta.url));
 fs.mkdirSync(target,{recursive:true});
 fs.writeFileSync(path.join(target,'lottie-light-5.13.0.mjs'),output);
 fs.writeFileSync(path.join(target,'lottie-LICENSE.txt'),license);
 console.log(JSON.stringify({version:'5.13.0',bytes:Buffer.byteLength(output),sha256:hash(output)}));
}
