import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createTour} from '../src/living-tour.mjs';
import {WORLDS,sceneLighting,react,state} from '../browser-extension/extension/living/model.mjs';
import {livingPreview,livingCollection} from '../src/living-collection.mjs';
function fixture(){let time=0,id=0;const queue=new Map(),changes=[];const tour=createTour({now:()=>time,setTimer:(fn,delay)=>{queue.set(++id,{fn,at:time+delay});return id;},clearTimer:k=>queue.delete(k),onChange:s=>changes.push(s)});return {tour,queue,changes,advance(ms){const target=time+ms;while(true){const entry=[...queue].sort((a,b)=>a[1].at-b[1].at)[0];if(!entry||entry[1].at>target)break;time=entry[1].at;queue.delete(entry[0]);entry[1].fn();}time=target;}};}
test('30-second tour advances all chapters and finishes once with no looping timer',()=>{const f=fixture();f.tour.reset(5);f.tour.play();assert.equal(f.queue.size,1);for(let i=1;i<5;i++){f.advance(6000);assert.equal(f.tour.snapshot().stage,i);assert.equal(f.queue.size,1);}f.advance(6000);assert.equal(f.tour.snapshot().complete,true);assert.equal(f.tour.snapshot().playing,false);assert.equal(f.queue.size,0);f.advance(60000);assert.equal(f.queue.size,0);});
test('pause preserves partial progress and resume continues rather than restarts',()=>{const f=fixture();f.tour.play();f.advance(3500);f.tour.pause();assert.equal(f.tour.snapshot().elapsed,3500);assert.equal(f.queue.size,0);f.advance(100000);assert.equal(f.tour.snapshot().elapsed,3500);f.tour.play();f.advance(4000);assert.equal(f.tour.snapshot().stage,1);});
test('hidden and unfocused time does not count toward the demonstration',()=>{const f=fixture();f.tour.reset(5);f.tour.play();f.advance(2000);f.tour.visible(false);assert.equal(f.queue.size,0);f.advance(120000);assert.equal(f.tour.snapshot().elapsed,2000);assert.equal(f.tour.snapshot().playing,true);f.tour.visible(true);f.advance(4000);assert.equal(f.tour.snapshot().stage,1);});
test('scrubbing is bounded, non-finite values are ignored and replay resets a completed journey',()=>{const f=fixture();f.tour.reset(5);f.tour.seek(.65);assert.equal(f.tour.snapshot().stage,3);f.tour.seek(NaN);assert.equal(f.tour.snapshot().stage,3);f.tour.seek(2);assert.equal(f.tour.snapshot().complete,true);f.tour.play();assert.equal(f.tour.snapshot().elapsed,0);f.tour.seek(-2);assert.equal(f.tour.snapshot().elapsed,0);});
test('repeated play or visibility calls never create multiple pending timers',()=>{const f=fixture();for(let i=0;i<50;i++){f.tour.play();f.tour.visible(true);}assert.equal(f.queue.size,1);f.tour.destroy();assert.equal(f.queue.size,0);f.tour.play();assert.equal(f.queue.size,0);});
test('switching worlds resets the correct chapter count and motion intent',()=>{const f=fixture();f.tour.reset(5);f.tour.play();f.advance(8000);f.tour.reset(4);assert.equal(f.queue.size,0);assert.equal(f.tour.snapshot().elapsed,0);assert.equal(f.tour.snapshot().playing,false);assert.throws(()=>f.tour.reset(100));});
test('website only offers the world chapters and weather supported by the shipped model',()=>{assert.deepEqual(WORLDS.map(w=>w.id),livingCollection.map(w=>w.id));assert.deepEqual(WORLDS[1].stages,['Earth orbit','Lunar approach','Asteroid passage','Jupiter flyby','Deep space']);assert.deepEqual(WORLDS[2].weather,['clear','rain','snow','fog']);assert.equal(sceneLighting('journey',4,5),'night');assert.equal(react(WORLDS[0],state(),'USER_IDLE').idle,true);});
test('preview makes timing, simulated events, optional motion and no live session explicit',()=>{const h=livingPreview();assert.match(h,/30-second journey/);assert.match(h,/events below are simulated/);assert.match(h,/do not earn focus minutes/);assert.match(h,/data-motion="false"/);assert.match(h,/not a live ChatGPT session/);assert.match(h,/Session moment/);});
test('website renderer modules come from the current extension source, including the articulated rig',async()=>{
 const source=name=>fs.readFileSync(new URL('../browser-extension/extension/living/'+name,import.meta.url),'utf8');
 const built=name=>fs.readFileSync(new URL('../dist/assets/'+name,import.meta.url),'utf8');
 assert.equal(built('living-model.js'),source('model.mjs'));
 assert.equal(built('living-companion-motion.js'),source('companion-motion.mjs'));
 assert.equal(built('living-companion-rig.js'),source('companion-rig.mjs').replaceAll("'./companion-motion.mjs'","'./living-companion-motion.js'"));
 const renderer=await import('../dist/assets/living-renderer.js');assert.equal(typeof renderer.createScene,'function');
 const quiet=await import('../browser-extension/extension/living/quiet-scene.mjs');assert.ok(built('living-runtime.css').startsWith(quiet.SCENE_CSS));
 assert.match(built('living-renderer.js'),/createCatRig/);assert.doesNotMatch(built('living-renderer.js'),/SCENE_CSS|QUIET_CSS/);
});
