import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {releaseSettings} from '../src/release.mjs';
const config=JSON.parse(fs.readFileSync('site.config.json'));
test('indexing requires an explicit production origin and opt-in',()=>{assert.equal(releaseSettings(config).indexable,false);assert.equal(releaseSettings(config,{SITE_URL:'https://chatdrobe.example',SITE_INDEXABLE:'true',VERCEL_ENV:'preview'}).indexable,false);assert.equal(releaseSettings(config,{SITE_URL:'https://chatdrobe.example',SITE_INDEXABLE:'true',VERCEL_ENV:'production'}).indexable,true);assert.throws(()=>releaseSettings(config,{SITE_INDEXABLE:'true'}));});
test('origins cannot contain credentials, paths or executable protocols',()=>{for(const url of ['http://example.com','https://user:pass@example.com','https://example.com/path','javascript:alert(1)'])assert.throws(()=>releaseSettings(config,{SITE_URL:url}));});
test('downloads require an approved repository release and matching checksum field',()=>{assert.throws(()=>releaseSettings({...config,downloadUrl:'https://bad.example/extension.zip'}));assert.throws(()=>releaseSettings({...config,downloadUrl:'https://bad.example/extension.zip',downloadSha256:'a'.repeat(64)}));assert.equal(releaseSettings({...config,downloadUrl:'https://github.com/onjoroge1/ChatDrobe/releases/download/v0.2.0/extension.zip',downloadSha256:'a'.repeat(64)}).sha.length,64);});
test('store links reject arbitrary origins and tracking queries',()=>{assert.throws(()=>releaseSettings({...config,storeUrl:'https://evil.example/detail/a/b'}));assert.ok(releaseSettings({...config,storeUrl:'https://chromewebstore.google.com/detail/chatdrobe/'+'a'.repeat(32)}).store);});
const manifest=JSON.parse(fs.readFileSync('dist/build-manifest.json')),pages=[...manifest.routes,'/404/'];
test('all pages have one heading, descriptions, social titles, and no inline scripts',()=>{for(const route of pages){const file=route==='/404/'?'dist/404.html':route==='/'?'dist/index.html':'dist'+route+'index.html',html=fs.readFileSync(file,'utf8');assert.equal((html.match(/<h1\b/g)||[]).length,1,route);assert.match(html,/<meta name="description" content="[^"]{40,}"/);assert.match(html,/property="og:title"/);assert.ok(!/<script(?![^>]*src=)[^>]*>/i.test(html));assert.ok(!/\son(?:click|load|error)=/i.test(html));assert.match(html,/href="\/beta-use\/"/);}});
function linkTarget(href,route,current){const url=new URL(href,'https://fixture.invalid'+route);let file=url.pathname==='/404/'?current:'dist'+url.pathname;if(file.endsWith('/'))file+='index.html';return {file,hash:decodeURIComponent(url.hash.slice(1))};}
test('internal URLs resolve by pathname, including query-bearing sign-in links; all anchors exist',()=>{
 assert.equal(linkTarget('/signin/?next=admin','/admin/','dist/admin/index.html').file,'dist/signin/index.html');assert.equal(linkTarget('/signin/?next=account','/account/','dist/account/index.html').file,'dist/signin/index.html');
 for(const route of pages){const current=route==='/404/'?'dist/404.html':route==='/'?'dist/index.html':'dist'+route+'index.html',html=fs.readFileSync(current,'utf8');for(const match of html.matchAll(/(?:href|src)="([^\"]+)"/g)){const href=match[1];if(!href.startsWith('/')&&!href.startsWith('#'))continue;const{file,hash}=linkTarget(href,route,current);assert.ok(fs.existsSync(file),`${route}: ${href}`);if(hash)assert.ok(fs.readFileSync(file,'utf8').includes(`id="${hash}"`),`${route}: ${href}`);}}
});
test('common budgets remain intact; account and scene code stay independently route-bounded',()=>{
 const bytes=f=>fs.statSync('dist/assets/'+f).size,files=fs.readdirSync('dist/assets');
 const coreJs=files.filter(f=>f.endsWith('.js')&&!f.startsWith('living-')&&!['accounts.js','account-link-ui.js'].includes(f)).reduce((sum,f)=>sum+bytes(f),0);assert.ok(coreJs<15000,`Core scripts: ${coreJs}`);assert.ok(bytes('client.js')<5000);
 assert.ok(bytes('accounts.js')<14000);assert.ok(bytes('account-link-ui.js')<8000);assert.ok(bytes('accounts.css')<5000);assert.ok(bytes('living-worlds.js')+bytes('living-tour.js')<11000);assert.ok(bytes('living-model.js')+bytes('living-renderer.js')<18000);assert.ok(bytes('living-runtime.css')<7000);
 const coreCss=files.filter(f=>f.endsWith('.css')&&!f.startsWith('living-')&&f!=='accounts.css').reduce((sum,f)=>sum+bytes(f),0);assert.ok(coreCss<24000,`Core CSS: ${coreCss}`);assert.ok(bytes('living-worlds.css')<8000);
 const illustrated=new Set(['/','/themes/','/features/','/premium/','/living-worlds/']),interactive=new Set(['/','/living-worlds/','/premium/']),accounts=new Set(['/signup/','/signin/','/account/','/admin/']);
 for(const route of pages){const file=route==='/404/'?'dist/404.html':route==='/'?'dist/index.html':'dist'+route+'index.html',html=fs.readFileSync(file,'utf8'),styles=[...html.matchAll(/<link\b[^>]*rel="stylesheet"[^>]*href="([^"]+)"/g)].map(m=>m[1]);assert.equal(styles.includes('/assets/living-worlds.css'),illustrated.has(route),route);assert.equal(html.includes('src="/assets/living-worlds.js"'),interactive.has(route),route);assert.equal(styles.includes('/assets/accounts.css'),accounts.has(route),route);assert.equal(html.includes('src="/assets/accounts.js"'),accounts.has(route),route);assert.equal(html.includes('src="/assets/account-link-ui.js"'),accounts.has(route),route);for(const deferred of ['living-renderer.js','living-model.js','living-runtime.css'])assert.ok(!html.includes(deferred),route+' eagerly loads '+deferred);const css=styles.reduce((sum,url)=>sum+fs.statSync('dist'+url).size,0);assert.ok(css<(illustrated.has(route)?32000:accounts.has(route)?29000:24000),`Per-route CSS: ${route} (${css})`);}
});
test('global security policy still forbids remote scripts and connections',()=>{const headers=JSON.parse(fs.readFileSync('src/deployment-headers.json')).headers[0].headers,csp=headers.find(h=>h.key==='Content-Security-Policy').value;assert.match(csp,/script-src 'self'/);assert.match(csp,/connect-src 'none'/);assert.match(csp,/frame-ancestors 'none'/);assert.match(csp,/style-src-attr 'unsafe-inline'/);assert.ok(!csp.includes("script-src 'self' 'unsafe-inline'"));});
