"""Extension account flow in actual Chromium with mocked worker replies; no native IPC."""
from pathlib import Path
import os,re
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1];E=ROOT/'extension';(ROOT/'preview').mkdir(exist_ok=True)
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH') or None,headless=True);page=b.new_page(viewport={'width':1100,'height':1100});errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 html=re.sub(r'<script[^>]*>.*?</script>|<link[^>]*>','',(E/'account.html').read_text());page.set_content(html);page.add_style_tag(content=(E/'upgrade.css').read_text());page.add_style_tag(content=(E/'account.css').read_text())
 page.add_script_tag(content="""window.calls=[];window.choice={kind:'living',id:'train',motion:'playful',name:'Cozy Train Journey'};window.state={premium:false,connected:false,linkCode:'ABCDE-12345-ABCDE-12345',linkExpires:1800000000,activation:{selection:choice,pending:true,state:'awaiting-access',reason:'Your choice is saved until Premium access is verified.'}};window.chrome={permissions:{request:async()=>true},runtime:{sendMessage:async m=>{calls.push(m.kind);return {ok:true,billing:state};}}};""")
 page.add_script_tag(content=(E/'account.js').read_text());expect(page.locator('#pairing')).to_be_visible();expect(page.locator('#pairing li')).to_have_count(3)
 expect(page.locator('#selected-name')).to_have_text('Cozy Train Journey');expect(page.locator('#selected-motion')).to_have_text('Motion: Playful');expect(page.locator('#selection-label')).to_have_text('SAVED WHILE YOU CONNECT');expect(page.locator('#step-signin')).to_have_attribute('aria-current','step');expect(page.locator('#step-signin')).to_have_attribute('data-complete','false');expect(page.locator('#step-connect')).to_have_attribute('data-complete','false')
 page.screenshot(path=str(ROOT/'preview/activation-instructions.png'),full_page=True)
 page.get_by_role('button',name='Continue on ChatDrobe').click();assert 'billing-website' in page.evaluate('calls');assert 'billing-start' not in page.evaluate('calls')
 page.evaluate("state={premium:false,connected:true,accountEmail:'owner@example.test',linkCode:'',lastErrorCode:'ACCESS_SIGNING_NOT_READY',lastError:'BILLING_SIGNING_PRIVATE_KEY has an invalid format. Keep this account connected.'}")
 page.get_by_role('button',name='Check access and world',exact=True).click();expect(page.locator('#setup')).to_be_visible();expect(page.locator('#plan')).to_have_text('Connected — Premium setup required');expect(page.locator('#continue')).to_be_hidden();expect(page.locator('#pairing')).to_be_hidden()
 page.screenshot(path=str(ROOT/'preview/activation-setup.png'),full_page=True)
 page.evaluate("state={premium:true,adminPremium:true,connected:true,accountEmail:'owner@example.test',linkCode:'',activation:{selection:choice,pending:false,state:'waiting',reason:'The selected appearance has not reached this ChatGPT tab yet.',action:'Open ChatGPT and refresh that tab once, then check again.'}}")
 page.get_by_role('button',name='Check access and world',exact=True).click();expect(page.locator('#setup')).to_be_hidden();expect(page.locator('#success')).to_be_visible();expect(page.locator('#plan')).to_have_text('Admin Premium — complimentary')
 expect(page.locator('#selection-label')).to_have_text('YOUR SAVED CHOICE');expect(page.locator('#application-status')).to_contain_text('has not reached');expect(page.locator('#step-apply')).to_have_attribute('aria-current','step');expect(page.locator('#step-apply')).to_have_attribute('data-complete','false')
 page.get_by_role('button',name='Open ChatGPT').click();assert 'billing-return' in page.evaluate('calls')
 page.evaluate("state.activation={selection:choice,pending:false,state:'blocked',reason:'No safe display space.',action:'Widen the window.'}");page.get_by_role('button',name='Check access and world',exact=True).click();expect(page.locator('#application-status')).to_have_text('No safe display space. Widen the window.');expect(page.locator('#selection-label')).to_have_text('YOUR SAVED CHOICE')
 page.evaluate("state.activation={selection:choice,pending:false,state:'displayed',reason:'Portal displayed; motion enabled.'}");page.get_by_role('button',name='Check access and world',exact=True).click();expect(page.locator('#selection-label')).to_have_text('CONFIRMED ON CHATGPT');expect(page.locator('#step-apply')).to_have_attribute('data-complete','true')
 for width in [360,390,768,1200]:
  page.set_viewport_size({'width':width,'height':1000});assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1')
 page.screenshot(path=str(ROOT/'preview/activation-ready.png'),full_page=True)
 page.evaluate("state={premium:false,connected:true,accountEmail:'member@example.test',activation:{selection:{kind:'theme',id:'mooncat',name:'Mooncat Café',motion:'still'},pending:false,requiresPremium:false,available:true,state:'displayed',reason:'Theme settings reached this ChatGPT tab.'}}")
 page.get_by_role('button',name='Check access and world',exact=True).click();expect(page.locator('#access-ready')).to_have_text('Account connected. Your Free theme is available.');expect(page.locator('#continue')).to_be_visible();expect(page.locator('#step-signin')).to_have_attribute('data-complete','true');expect(page.locator('#step-connect')).to_have_attribute('data-complete','true')
 assert not errors,errors;b.close();print('7 activation UI groups passed: saved choice/current-code link, setup failure, signed access/return, waiting versus displayed, blocked layout recovery, responsive layouts, connected Free appearance.')
