const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const P=require('../extension/prefs.js'),C=require('../extension/core.js'),A=require('../extension/adapter.js');
function fixture(){
 class Node{constructor(){this.attrs=new Map();this.children=[];this.isConnected=false;this.id='';}getAttribute(k){return this.attrs.get(k)??null;}setAttribute(k,v){this.attrs.set(k,String(v));}removeAttribute(k){this.attrs.delete(k);}append(n){n.isConnected=true;this.children.push(n);}remove(){this.isConnected=false;}}
 const html=new Node(),props=new Map();html.style={getPropertyValue:k=>props.get(k)?.[0]||'',getPropertyPriority:k=>props.get(k)?.[1]||'',setProperty:(k,v,p='')=>props.set(k,[v,p]),removeProperty:k=>props.delete(k)};
 const listeners=new Map(),doc={documentElement:html,body:new Node(),hidden:false,createElement:()=>new Node(),addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:name=>listeners.delete(name)};
 return {doc,html,props,listeners};
}
test('page and workspace preference schemas remain identical',()=>{for(let i=0;i<100;i++){const p={theme:C.THEMES[i%12].id,font:i%3?'serif':'mono',width:i*30,fontSize:i,lineHeight:i/5,accent:i%2?'#aabbcc':'invalid',motion:i%2===0};assert.deepEqual(P.prefs(p),C.prefs(p));}});
test('one inert node, idempotent writes, no message traversal',()=>{const f=fixture(),a=A.create(f.doc);a.apply({});const d=a.diagnostics();assert.equal(d.extraDOMNodes,1);a.apply({});assert.equal(a.diagnostics().writeCount,d.writeCount);assert.equal(a.diagnostics().applyCount,1);assert.equal(f.doc.body.children.length,1);});
test('cross-mode theme switch changes only theme and scheme root attributes',()=>{const f=fixture(),a=A.create(f.doc);a.apply({mode:'theme'});const before=a.diagnostics().writeCount;a.apply({theme:'circuit',mode:'theme'});assert.equal(a.diagnostics().writeCount-before,2);});
test('pause restores captured variables and never changes native class',()=>{const f=fixture();f.html.setAttribute('class','dark native-app');f.html.style.setProperty('--md-width','791px','important');const a=A.create(f.doc);a.apply({theme:'circuit'});a.apply({enabled:false});assert.equal(f.html.getAttribute('data-md-enabled'),null);assert.equal(f.html.getAttribute('class'),'dark native-app');assert.equal(f.html.style.getPropertyValue('--md-width'),'791px');assert.equal(f.html.style.getPropertyPriority('--md-width'),'important');assert.equal(a.diagnostics().extraDOMNodes,0);});
test('decoration off has zero added connected elements',()=>{const f=fixture(),a=A.create(f.doc);a.apply({decoration:false});assert.equal(a.diagnostics().extraDOMNodes,0);a.apply({decoration:true});assert.equal(a.diagnostics().extraDOMNodes,1);a.apply({decoration:false});assert.equal(a.diagnostics().extraDOMNodes,0);});
test('hidden page updates animation pause gate without theme apply',()=>{const f=fixture(),a=A.create(f.doc);a.apply({motion:true});f.doc.hidden=true;f.listeners.get('visibilitychange')();assert.equal(f.html.getAttribute('data-md-visible'),'false');assert.equal(a.diagnostics().applyCount,1);});
test('startup before body waits for DOMContentLoaded rather than polling',()=>{const f=fixture(),body=f.doc.body;f.doc.body=null;const a=A.create(f.doc);a.apply({});assert.equal(a.diagnostics().extraDOMNodes,0);f.doc.body=body;f.listeners.get('DOMContentLoaded')();assert.equal(a.diagnostics().extraDOMNodes,1);});
test('dispose restores styling, removes owned node, and detaches listeners',()=>{const f=fixture(),a=A.create(f.doc);a.apply({});a.dispose();assert.equal(a.diagnostics().extraDOMNodes,0);assert.equal(f.listeners.size,0);const before=a.diagnostics().writeCount;a.apply({});assert.equal(a.diagnostics().writeCount,before);});
test('eager page scripts have no polling, DOM scans, or UI imports',()=>{for(const file of ['boot.js','adapter.js']){const s=fs.readFileSync(require('node:path').join(__dirname,'../extension',file),'utf8');assert.ok(!/setTimeout\s*\(|setInterval\s*\(|querySelector|requestAnimationFrame|innerHTML|textContent|core\.js|workspace\.js/.test(s),file);}});
test('native side panel is separate from the page entry points',()=>{const m=require('../extension/manifest.json');assert.equal(m.side_panel.default_path,'workspace.html');assert.deepEqual(m.content_scripts[0].js,['prefs.js','adapter.js','boot.js']);assert.equal(m.content_scripts[0].run_at,'document_start');assert.equal(m.content_scripts[0].all_frames,false);});
test('small-node motion only; no main background-position animation',()=>{const css=fs.readFileSync(require('node:path').join(__dirname,'../extension/theme.css'),'utf8');assert.ok(!/background-position|backdrop-filter:\s*(?!none)[a-z]/.test(css));assert.match(css,/prefers-reduced-motion/);assert.match(css,/animation-play-state:paused/);assert.match(css,/transform:translateY/);});
test('new and legacy appearance files both import',()=>{for(const format of ['chatdrobe-appearance','mooddock-appearance'])assert.equal(C.importAppearance(JSON.stringify({format,version:1,prefs:{theme:'comic'}})).theme,'comic');});

test('native appearance observer is restricted to root attributes without subtree',()=>{const src=fs.readFileSync(require('node:path').join(__dirname,'../extension/adapter.js'),'utf8');assert.match(src,/observer.observe\(html,\{attributes:true,attributeFilter:\['class','data-theme','data-color-scheme'\]\}\)/);assert.ok(!/subtree:true/.test(src));});
