const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('../extension/core.js');
function worker(){
 const id='extension-id',messages=[],store={mooddock:C.state({notes:'private note'})};let listener,level,configured=false;
 const chrome={runtime:{id,onMessage:{addListener:fn=>listener=fn},onInstalled:{addListener:()=>{}}},storage:{local:{setAccessLevel:async v=>{level=v.accessLevel;},get:async key=>Object.fromEntries((Array.isArray(key)?key:[key]).map(k=>[k,structuredClone(store[k])])),set:async v=>{for(const[k,val]of Object.entries(v))store[k]=structuredClone(val);}}},sidePanel:{setPanelBehavior:async()=>{configured=true;}},tabs:{query:async()=>[{id:1}],sendMessage:async(id,message)=>{messages.push(structuredClone(message));return{ok:true,stats:{applyCount:1}};}}};
 const ctx=vm.createContext({chrome,MoodDockCore:C,ChatDrobeFocus:require('../extension/focus-state.js'),crypto:require('node:crypto').webcrypto,ChatDrobeAccess:require('../extension/access.js'),ChatDrobeCommerceConfig:{channel:'private-beta',allowTesterPreview:true},URL,console,importScripts:()=>{}});vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../extension/background.js'),'utf8'),ctx);
 function send(kind,action,url='chrome-extension://extension-id/workspace.html',override={}){return new Promise(resolve=>{const result=listener({scope:'mooddock',kind,action},{id,url,...override},resolve);if(result===false)resolve({ignored:true});});}
 return{send,store,messages,get level(){return level;},get configured(){return configured;}};
}
test('migrates existing state and restricts storage to trusted contexts',async()=>{const w=worker(),r=await w.send('read');assert.equal(r.state.notes,'private note');assert.equal(w.level,'TRUSTED_CONTEXTS');assert.equal(w.configured,true);assert.equal(w.store['mooddock:prefs-v2'].revision,0);});
test('page preference response excludes notes and the full workspace',async()=>{const w=worker(),r=await w.send('read-prefs',null,'https://chatgpt.com/c/example');assert.equal(r.ok,true);assert.equal(r.state,undefined);assert.equal(r.snapshot.notes,undefined);assert.equal(r.snapshot.prefs.theme,'mooncat');});
test('page cannot read or mutate workspace records',async()=>{const w=worker();for(const kind of ['read','mutate','diagnostics','idle-preview']){const r=await w.send(kind,{type:'notes',value:'hacked'},'https://chatgpt.com/c/example');assert.equal(r.ok,false);}assert.equal(w.store.mooddock.notes,'private note');});
test('off-origin and wrong-extension requests are rejected',async()=>{const w=worker();assert.equal((await w.send('read-prefs',null,'https://chatgpt.com.evil.example')).ok,false);assert.equal((await w.send('read',null,undefined,{id:'other'})).ignored,true);});
test('saving a note does not broadcast preferences',async()=>{const w=worker();const r=await w.send('mutate',{type:'notes',value:'saved'});assert.equal(r.state.notes,'saved');assert.equal(w.messages.length,0);});
test('theme changes increment revision and send only sanitized preferences',async()=>{const w=worker();const r=await w.send('mutate',{type:'settings',value:{theme:'circuit',css:'malicious'}});assert.equal(r.state.prefs.theme,'circuit');assert.equal(w.messages.length,1);assert.equal(w.messages[0].snapshot.revision,1);assert.equal(w.messages[0].snapshot.prefs.css,undefined);assert.equal(w.messages[0].state,undefined);});
test('queued mutations preserve concurrent note and prompt updates',async()=>{const w=worker();await Promise.all([w.send('mutate',{type:'notes',value:'retained'}),w.send('mutate',{type:'prompt-add',id:'1',title:'Prompt',body:'Text'})]);assert.equal(w.store.mooddock.notes,'retained');assert.equal(w.store.mooddock.prompts.length,1);});
test('atomic Free selection clears a stored Living scene and publishes its actual revision',async()=>{const w=worker();w.store.mooddock=C.state({notes:'private',prefs:{livingEnabled:true,livingWorld:'train',livingMotion:true}});const r=await w.send('mutate',{type:'select-experience',value:{kind:'theme',id:'ocean',motion:'still'}});assert.equal(r.ok,true);assert.equal(r.state.prefs.theme,'ocean');assert.equal(r.state.prefs.livingEnabled,false);assert.equal(r.desiredPrefs.livingEnabled,false);assert.equal(r.revision,w.store['mooddock:prefs-v2'].revision);assert.equal(r.state.notes,'private');});
test('atomic Premium selection cannot bypass the worker entitlement gate',async()=>{const w=worker();for(const value of [{kind:'living',id:'tokyo',motion:'still'},{kind:'companion',id:'cat',motion:'still'},{kind:'theme',id:'mooncat',motion:'subtle'}]){const r=await w.send('mutate',{type:'select-experience',value});assert.equal(r.ok,false);assert.equal(w.store.mooddock.prefs.livingEnabled,false);assert.equal(w.store.mooddock.prefs.idleMode,'off');assert.equal(w.store.mooddock.prefs.motion,false);}});
test('backup restore preserves locked desired appearance without granting account access',async()=>{const w=worker();const backup=C.state({prefs:{livingEnabled:true,livingWorld:'train',livingMotion:true,wordBitesConsent:true},notes:'Restored'});const r=await w.send('mutate',{type:'restore-backup',value:backup});assert.equal(r.ok,true);assert.equal(r.access.premium,false);assert.equal(r.state.prefs.livingEnabled,false);assert.equal(r.desiredPrefs.livingEnabled,true);assert.equal(r.desiredPrefs.livingMotion,true);assert.equal(r.desiredPrefs.wordBitesConsent,false);assert.equal(r.state.notes,'Restored');const publicReply=await w.send('read-prefs',null,'https://chatgpt.com/c/a');assert.equal(publicReply.desiredPrefs,undefined);assert.equal(publicReply.snapshot.prefs.livingEnabled,false);});
