const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto').webcrypto;
const C=require('../extension/core.js'),A=require('../extension/access.js'),F=require('../extension/focus-state.js');
function worker(shared){
 const store=shared||{mooddock:C.state({notes:'private note'}),'chatdrobe:access-beta-v1':{testerPreview:true}},sent=[];let listener,alarmListener;const alarms=new Map();let clock=1000000;
 class Clock extends Date{static now(){return clock;}}
 const chrome={runtime:{id:'test',onMessage:{addListener:f=>listener=f},onInstalled:{addListener:()=>{}},onStartup:{addListener:()=>{}}},storage:{local:{setAccessLevel:async()=>{},get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,structuredClone(store[k])])),set:async value=>Object.assign(store,structuredClone(value))}},sidePanel:{setPanelBehavior:async()=>{}},alarms:{onAlarm:{addListener:f=>alarmListener=f},get:async n=>alarms.get(n),create:async(n,a)=>alarms.set(n,{scheduledTime:a.when}),clear:async n=>alarms.delete(n)},tabs:{query:async()=>[{id:1},{id:2}],sendMessage:async(id,m)=>{sent.push({id,...structuredClone(m)});return{ok:true};}}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../extension/background.js'),'utf8'),{chrome,URL,console,Date:Clock,crypto,importScripts:()=>{},MoodDockCore:C,ChatDrobeAccess:A,ChatDrobeFocus:F,ChatDrobeCommerceConfig:{channel:'private-beta',allowTesterPreview:true}});
 const send=(kind,action,url='chrome-extension://test/workspace.html')=>new Promise(resolve=>listener({scope:'mooddock',kind,action},{id:'test',url},resolve));
 return {store,sent,alarms,send,setTime:n=>clock=n,fire:async()=>{alarmListener({name:'chatdrobe:focus-complete'});await send('read');}};
}
test('focus start broadcasts a shared session to tabs, without notes or aggregate statistics',async()=>{const w=worker();await w.send('mutate',{type:'timer',value:1300000});assert.equal(w.alarms.size,1);assert.equal(w.sent.length,2);assert.equal(w.sent[0].snapshot.focus.status,'running');assert.equal(w.sent[0].snapshot.notes,undefined);assert.equal(w.sent[0].snapshot.completed,undefined);assert.equal(w.store.mooddock.notes,'private note');});
test('duplicate alarm callbacks settle a focus session once across multiple tabs',async()=>{const w=worker();await w.send('mutate',{type:'timer',value:1300000});w.setTime(1300000);await w.fire();await w.fire();const r=await w.send('living-state');assert.equal(r.progress.completed,1);assert.equal(r.progress.minutes,5);assert.equal(w.alarms.size,0);});
test('cold service worker recreates missing alarm from saved session and does not lose notes',async()=>{const a=worker();await a.send('mutate',{type:'timer',value:1300000});const b=worker(a.store);await b.send('read');assert.equal(b.alarms.size,1);b.setTime(1400000);await b.fire();assert.equal((await b.send('living-state')).progress.completed,1);assert.equal(b.store.mooddock.notes,'private note');});
test('page scripts cannot inspect aggregate progress or reset it; upgrade page also denied',async()=>{const w=worker();for(const url of ['https://chatgpt.com/c/test','chrome-extension://test/upgrade.html'])for(const kind of ['living-state','living-reset-progress'])assert.equal((await w.send(kind,null,url)).ok,false);});
test('cancelling and clearing progress removes alarm and never changes saved private tools',async()=>{const w=worker();await w.send('mutate',{type:'timer',value:1300000});await w.send('mutate',{type:'timer',value:0});w.setTime(1400000);await w.fire();assert.equal((await w.send('living-state')).progress.completed,0);await w.send('living-reset-progress');assert.equal(w.alarms.size,0);assert.equal(w.store.mooddock.notes,'private note');assert.equal(w.store.mooddock.timerUntil,0);});
test('invalid timer durations fail without creating a session or changing timer state',async()=>{const w=worker();assert.equal((await w.send('mutate',{type:'timer',value:1000500})).ok,false);assert.equal(w.store.mooddock.timerUntil,0);assert.equal(w.alarms.size,0);});
