const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
async function setup(prefs){let listener;const loads=[],configs=[],idle=[],applies=[];const P=require('../extension/prefs.js');
 const chrome={runtime:{id:'fixture',getURL:p=>p,onMessage:{addListener:f=>listener=f},sendMessage:async()=>({ok:true,snapshot:{revision:0,prefs}})}};
 const context=vm.createContext({chrome,document:{},location:{origin:'https://chatgpt.com'},window:{addEventListener:()=>{}},ChatDrobePrefs:P,ChatDrobeAdapter:{create:()=>({apply:p=>applies.push(p),diagnostics:()=>({})})},__import:async path=>{loads.push(path);return path==='living/engine.mjs'?{createEnvironment:()=>({configure:p=>configs.push(p)})}:{createIdleController:()=>({configure:p=>idle.push(p)})};}});
 vm.runInContext(fs.readFileSync('extension/boot.js','utf8').replace(/\bimport\(/g,'__import('),context);await new Promise(setImmediate);await new Promise(setImmediate);
 return {loads,configs,idle,applies,message:p=>listener({scope:'mooddock',kind:'prefs',snapshot:{revision:1,prefs:p}},{id:'fixture'},()=>{})};
}
test('natural mode uses one shared inert scene, hides the old decoration and keeps the selected static theme',async()=>{const x=await setup({theme:'starlit',idleMode:'natural'});assert.deepEqual(x.loads,['living/engine.mjs']);assert.equal(x.configs[0].livingEnabled,true);assert.equal(x.configs[0].livingCompanionOnly,true);assert.equal(x.configs[0].livingMotion,false,'Still must not silently animate');assert.equal(x.applies[0].theme,'starlit');assert.equal(x.applies[0].decoration,false);assert.equal(x.idle.length,0);});
test('disabling natural mode disables the scene and restores normal static appearance',async()=>{const x=await setup({theme:'starlit',idleMode:'natural'});x.message({theme:'starlit',idleMode:'off'});assert.equal(x.configs.at(-1).livingEnabled,false);assert.equal(x.applies.at(-1).decoration,true);});
test('Free entitlement strips natural mode before the boot adapter can load it',async()=>{const A=require('../extension/access.js'),P=require('../extension/prefs.js');const prefs=A.effective(P.prefs({theme:'starlit',idleMode:'natural'}),{premium:false});const x=await setup(prefs);assert.deepEqual(x.loads,[]);assert.equal(x.applies[0].theme,'mooncat');});
test('explicit Living World wins over a remembered natural-companion preference',async()=>{const x=await setup({theme:'bridge',idleMode:'natural',livingEnabled:true,livingWorld:'starship'});assert.equal(x.loads.filter(x=>x==='living/engine.mjs').length,1);assert.equal(x.configs[0].livingWorld,'starship');assert.equal(x.configs[0].livingCompanionOnly,undefined);assert.equal(x.idle.length,0);});
test('existing cat walking opt-in upgrades to Natural without a storage migration or new click',async()=>{const x=await setup({theme:'starlit',companion:'theme',idleMode:'stroll'});assert.deepEqual(x.loads,['living/engine.mjs']);assert.equal(x.configs[0].livingCompanionOnly,true);assert.equal(x.applies[0].theme,'starlit');});
test('decoration motion alone stays static while explicit imported companions restore without content consent',async()=>{const x=await setup({theme:'starlit',motion:true,idleMode:'off'});assert.deepEqual(x.loads,[]);const C=require('../extension/core.js');const p=C.importAppearance(JSON.stringify({format:'chatdrobe-appearance',version:1,prefs:{theme:'starlit',livingMotion:true,idleMode:'natural',wordBitesConsent:true}}));const y=await setup(p);assert.deepEqual(y.loads,['living/engine.mjs']);assert.equal(y.configs[0].livingMotion,true);assert.equal(y.configs[0].wordBitesConsent,false);});
test('non-cat Explorer routines retain their existing lazy controller',async()=>{const x=await setup({theme:'rally',companion:'theme',idleMode:'stroll'});assert.deepEqual(x.loads,['idle.js']);assert.equal(x.configs.length,0);});
