const test=require('node:test'),assert=require('node:assert/strict'),A=require('../extension/access.js'),C=require('../extension/core.js'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const beta={channel:'private-beta',allowTesterPreview:true};
test('Free by default; paid booleans, redirect params and unknown data never unlock',()=>{for(const x of [{},{paid:true},{premium:true},{plan:'premium'},{success:true},{isPro:true}])assert.equal(A.access(x,beta).premium,false);});
test('private preview requires explicit flag and beta build; production never trusts it',()=>{assert.equal(A.access({testerPreview:true},beta).premium,true);assert.equal(A.access({testerPreview:true},{...beta,channel:'production'}).premium,false);assert.equal(A.access({testerPreview:true},{...beta,allowTesterPreview:false}).premium,false);});
test('Free policy removes premium theme and motion but preserves accessible reading choices',()=>{const p=A.effective(C.prefs({theme:'sentinel',font:'serif',mode:'light',width:1000,idleMode:'stroll',motion:true}),A.access({},beta));assert.equal(p.theme,'mooncat');assert.equal(p.font,'serif');assert.equal(p.mode,'light');assert.equal(p.width,1000);assert.equal(p.idleMode,'off');assert.equal(p.motion,false);});
test('appearance imports and workspace reducer contain no test or paid grants',()=>{const p=C.importAppearance(JSON.stringify({format:'chatdrobe-appearance',version:1,prefs:{theme:'sentinel',testerPreview:true,paid:true,wordBitesConsent:true}}));assert.equal(p.testerPreview,undefined);assert.equal(p.paid,undefined);assert.equal(p.wordBitesConsent,false);assert.equal(A.effective(p,A.access({},beta)).theme,'mooncat');});
test('checkout remains disabled even when unverified URL or ready flags are supplied',()=>{assert.equal(A.checkout({checkoutEnabled:true,licensingReady:true,checkoutUrl:'https://buy.stripe.com/pretend'}).ready,false);});
test('all local extension pages reference included scripts and styles; manifest at root',()=>{const E=path.join(__dirname,'../extension');for(const f of ['workspace.html','upgrade.html'])for(const [,file] of fs.readFileSync(path.join(E,f),'utf8').matchAll(/(?:src|href)="([^"#]+)"/g))assert.ok(fs.existsSync(path.join(E,file)),file);assert.ok(fs.existsSync(path.join(E,'manifest.json')));});
test('billing code stays out of ChatGPT content scripts and website permission is optional',()=>{const m=require('../extension/manifest.json');assert.deepEqual(m.host_permissions,['https://chatgpt.com/*']);assert.ok(!m.content_scripts[0].js.includes('access.js'));assert.deepEqual(m.optional_host_permissions,['https://www.chatdrobe.com/*']);assert.equal(m.content_security_policy.extension_pages.includes('connect-src https://www.chatdrobe.com'),true);for(const f of ['entitlement.js','billing-client.js'])assert.ok(!m.content_scripts[0].js.includes(f));});
test('initial appearance defaults to light while explicit stored choices are preserved',()=>{assert.equal(C.prefs({}).mode,'light');for(const mode of ['dark','light','theme','system'])assert.equal(C.prefs({mode}).mode,mode);});
function worker(){
 const id='sample',store={mooddock:C.state({notes:'private',prefs:{theme:'sentinel'}})},tabs=[],pageUpdates=[];let listener;
 const chrome={runtime:{id,getURL:p=>'chrome-extension://sample/'+p,onMessage:{addListener:f=>listener=f},onInstalled:{addListener:()=>{}}},storage:{local:{setAccessLevel:async()=>{},get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,structuredClone(store[k])])),set:async obj=>Object.assign(store,structuredClone(obj))}},sidePanel:{setPanelBehavior:async()=>{}},tabs:{query:async()=>[{id:3}],create:async d=>{tabs.push(d);return{id:9};},sendMessage:async(id,m)=>{pageUpdates.push(m);return{ok:true};}}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../extension/background.js'),'utf8'),{chrome,URL,console,importScripts:()=>{},MoodDockCore:C,ChatDrobeFocus:require('../extension/focus-state.js'),crypto:require('node:crypto').webcrypto,ChatDrobeAccess:A,ChatDrobeCommerceConfig:beta});
 return {tabs,store,pageUpdates,send:(message,where='workspace.html')=>new Promise(resolve=>{const ret=listener({scope:'mooddock',...message},{id,url:where.startsWith('https:')?where:'chrome-extension://sample/'+where},resolve);if(ret===false)resolve({ignored:true});})};
}
test('worker gates direct Premium changes, preserves user data and opens only its fixed upgrade page',async()=>{const w=worker();let r=await w.send({kind:'read'});assert.equal(r.state.prefs.theme,'mooncat');assert.equal(r.state.notes,'private');r=await w.send({kind:'mutate',action:{type:'settings',value:{theme:'reactor'}}});assert.equal(r.ok,false);await w.send({kind:'open-upgrade',world:'reactor',url:'https://evil.example'});assert.equal(w.tabs[0].url,'chrome-extension://sample/upgrade.html?world=reactor');assert.equal(w.store.mooddock.notes,'private');});
test('worker preview action is separate from settings and denied to content scripts',async()=>{const w=worker();assert.equal((await w.send({kind:'tester-preview',enabled:true},'https://chatgpt.com/c/example')).ok,false);assert.equal((await w.send({kind:'tester-preview',enabled:true})).access.testerPreview,true);assert.equal((await w.send({kind:'mutate',action:{type:'settings',value:{theme:'reactor'}}})).ok,true);assert.equal((await w.send({kind:'tester-preview',enabled:false})).state.prefs.theme,'mooncat');});
test('upgrade page cannot read workspace content or grant paid access',async()=>{const w=worker();assert.equal((await w.send({kind:'read'},'upgrade.html')).ok,false);assert.equal((await w.send({kind:'tester-preview',enabled:true},'upgrade.html')).ok,false);assert.equal((await w.send({kind:'start-checkout'},'upgrade.html')).ok,false);});
