const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
async function fixture(){const {createQuietPolicy}=await import('../extension/living/quiet-policy.mjs');let t=0,id=0;const q=new Map(),changes=[];const policy=createQuietPolicy({now:()=>t,setTimer:(fn,ms)=>{q.set(++id,{fn,at:t+ms});return id;},clearTimer:k=>q.delete(k),onChange:s=>changes.push({at:t,...s})});return{policy,q,changes,advance(ms){const end=t+ms;while(true){const e=[...q].sort((a,b)=>a[1].at-b[1].at)[0];if(!e||e[1].at>end)break;t=e[1].at;q.delete(e[0]);e[1].fn();}t=end;}};}
test('no opt-in means no timer or movement',async()=>{const f=await fixture();f.policy.configure({enabled:false,active:true});f.advance(900000);assert.equal(f.q.size,0);assert.equal(f.policy.snapshot().pose,'rest');});
test('progressive idle unlocks richer finite actions with long gaps, then sleeps',async()=>{const f=await fixture();f.policy.configure({enabled:true,active:true});f.advance(44999);assert.equal(f.policy.snapshot().pose,'rest');f.advance(1);assert.equal(f.policy.snapshot().pose,'look');f.advance(600000);const runs=f.changes.filter(x=>!['rest','sleep'].includes(x.pose));const names=[...new Set(runs.map(x=>x.pose))];for(const pose of ['look','groom','scratch','stretch','knead','curl'])assert.ok(names.includes(pose),pose);for(let i=1;i<runs.length;i++)assert.ok(runs[i].at-runs[i-1].at>=75000);assert.ok(runs.length<=8);assert.equal(f.policy.snapshot().pose,'sleep');assert.equal(f.q.size,0);});
test('subtle mode never graduates to the complex behaviors',async()=>{const f=await fixture();f.policy.configure({enabled:true,active:true,behavior:'subtle'});f.advance(610000);for(const x of f.changes)assert.ok(['rest','blink','breathe','ears','sleep'].includes(x.pose),x.pose);assert.equal(f.q.size,0);});
test('input immediately cancels a routine and frequent events keep at most one timer',async()=>{const f=await fixture();f.policy.configure({enabled:true,active:true});f.advance(45000);for(let i=0;i<1000;i++)f.policy.activity();assert.equal(f.policy.snapshot().pose,'rest');assert.equal(f.policy.snapshot().busy,true);assert.equal(f.q.size,1);f.advance(10000);assert.equal(f.policy.snapshot().busy,false);f.advance(35000);assert.equal(f.policy.snapshot().pose,'rest','cooldown survives activity');});
test('background, focus suppression and opt-out clear timers without a catch-up show',async()=>{for(const patch of [{active:false},{quiet:true},{enabled:false}]){const f=await fixture();f.policy.configure({enabled:true,active:true});f.advance(250000);f.policy.configure({enabled:true,active:true,...patch});assert.equal(f.q.size,0);f.advance(900000);assert.equal(f.q.size,0);f.policy.configure({enabled:true,active:true});assert.equal(f.policy.snapshot().pose,'rest');f.advance(44000);assert.equal(f.policy.snapshot().pose,'rest');f.policy.dispose();assert.equal(f.q.size,0);}});
test('spacecraft follows its own richer sequence, not cat poses',async()=>{const f=await fixture();f.policy.configure({enabled:true,active:true,world:'starship'});f.advance(610000);const names=new Set(f.changes.map(x=>x.pose));for(const p of ['inspect','calibrate','dock','sleep'])assert.ok(names.has(p));assert.ok(!names.has('groom'));assert.equal(f.q.size,0);});
test('changing companion behavior resets choreography without preserving old timers',async()=>{const f=await fixture();f.policy.configure({enabled:true,active:true});f.advance(300000);f.policy.configure({enabled:true,active:true,behavior:'subtle'});assert.equal(f.policy.snapshot().pose,'rest');assert.equal(f.q.size,1);f.advance(45000);assert.equal(f.policy.snapshot().pose,'blink');});
test('sleep never produces an unattended perpetual timer; returning restarts conservatively',async()=>{const f=await fixture();f.policy.configure({enabled:true,active:true});f.advance(1200000);assert.equal(f.q.size,0);f.policy.activity();assert.equal(f.policy.snapshot().pose,'rest');f.advance(44000);assert.equal(f.policy.snapshot().pose,'rest');f.policy.dispose();f.policy.activity();assert.equal(f.q.size,0);});
test('shared renderer removes labels and contains no network or transcript access',()=>{for(const file of ['quiet-scene.mjs','companion-rig.mjs','companion-motion.mjs']){const source=fs.readFileSync(new URL('../extension/living/'+file,'file://'+__filename),'utf8');assert.doesNotMatch(source,/fetch\s*\(|innerHTML|textContent|setInterval|requestAnimationFrame/);}assert.match(fs.readFileSync('extension/living/quiet-scene.mjs','utf8'),/querySelector\('\.caption'\)\?\.remove/);});
test('host adapter observes input occurrence and selection collapse, never selected text',()=>{const s=fs.readFileSync('extension/living/engine.mjs','utf8');assert.doesNotMatch(s,/event\.key|event\.data|\.value\b|\.textContent\b|\.toString\(|setInterval\(/);for(const event of ['compositionstart','compositionend','selectionchange'])assert.ok(s.includes(event));const m=require('../extension/manifest.json');assert.deepEqual(m.permissions,['storage','sidePanel','alarms']);assert.deepEqual(m.host_permissions,['https://chatgpt.com/*']);});
