const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const {generateKeyPairSync,sign,createHash,webcrypto}=require('node:crypto');
const Core=require('../extension/core.js'),Focus=require('../extension/focus-state.js'),Access=require('../extension/access.js'),Billing=require('../extension/billing-client.js'),Entitlement=require('../extension/entitlement.js');
const hash=v=>createHash('sha256').update(v).digest('hex');
function worker({existing=true}={}){
 const id='a'.repeat(32),data={mooddock:Core.state({notes:'PRIVATE NOTE'}),'chatdrobe:access-beta-v1':{testerPreview:true,premium:true}},broadcasts=[],opened=[],activated=[],alarms=new Map(),alarmHandlers=[];
 let permission=false,linked=false,plan='free',source=null,now=1700000000000,listener,level;
 const {privateKey,publicKey}=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),config={channel:'sandbox',allowTesterPreview:false,billingOrigin:'https://www.chatdrobe.com',entitlementKey:{keyId:'test',publicJwk:publicKey.export({format:'jwk'})}};
 const storage={setAccessLevel:async v=>level=v.accessLevel,get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,structuredClone(data[k])])),set:async v=>Object.assign(data,structuredClone(v))};
 const requests=[];
 const fetcher=async(url,opts)=>{const action=new URL(url).searchParams.get('action'),secret=opts.headers.Authorization.slice(7);requests.push(action);let body;
  if(action==='start')body={code:'ABCDE-12345-ABCDE-12345',expiresAt:now/1000+600,verificationUrl:'https://www.chatdrobe.com/account/#link=ABCDE-12345-ABCDE-12345'};
  else if(action==='poll')body={linked,account:{email:'member@example.test'}};
  else if(action==='entitlement'){
   const h={alg:'ES256',typ:'JWT',kid:'test'},p={iss:'chatdrobe-billing-test',aud:'chatdrobe-extension',sub:hash('account'),did:hash(secret),environment:'test',plan,accessSource:source||(plan==='plus'?'stripe_test':'free'),iat:now/1000,exp:now/1000+600};
   const raw=[h,p].map(x=>Buffer.from(JSON.stringify(x)).toString('base64url')).join('.');body={linked:true,plan,environment:'test',account:{email:'member@example.test'},token:raw+'.'+sign('sha256',Buffer.from(raw),{key:privateKey,dsaEncoding:'ieee-p1363'}).toString('base64url')};
  }else body={ok:true};return new Response(JSON.stringify(body),{status:200});
 };
 const chrome={runtime:{id,getURL:p=>'chrome-extension://'+id+'/'+p,onMessage:{addListener:fn=>listener=fn},onInstalled:{addListener:()=>{}},onStartup:{addListener:()=>{}}},storage:{local:storage},permissions:{contains:async()=>permission},sidePanel:{setPanelBehavior:async()=>{}},tabs:{query:async()=>existing?[{id:1,windowId:2,active:true}]:[],update:async(id,v)=>activated.push({id,...v}),create:async v=>opened.push(v.url),sendMessage:async(_,v)=>broadcasts.push(structuredClone(v)),onUpdated:{addListener:()=>{}}},alarms:{get:async k=>alarms.get(k),create:async(k,v)=>alarms.set(k,v),clear:async k=>alarms.delete(k),onAlarm:{addListener:fn=>alarmHandlers.push(fn)}}};
 const ctx=vm.createContext({chrome,MoodDockCore:Core,ChatDrobeFocus:Focus,ChatDrobeAccess:Access,ChatDrobeCommerceConfig:config,ChatDrobeBilling:{...Billing,create:o=>Billing.create({...o,fetcher,now:()=>now,cryptoApi:webcrypto,verify:Entitlement.verify})},crypto:webcrypto,URL,console,importScripts:()=>{}});
 vm.runInContext(fs.readFileSync(path.join(__dirname,'../extension/background.js'),'utf8'),ctx);
 const send=(kind,extra={},from='workspace.html')=>new Promise(resolve=>{const u=from.startsWith('http')?from:'chrome-extension://'+id+'/'+from;const r=listener({scope:'mooddock',kind,...extra},{id,url:u},resolve);if(r===false)resolve({ignored:true});});
 return {send,data,broadcasts,opened,activated,requests,alarms,permit:()=>permission=true,link:()=>linked=true,plus:()=>{plan='plus';source='stripe_test';},admin:()=>{plan='plus';source='admin';},free:()=>{plan='free';source='free';},advance:ms=>now+=ms,expire:()=>alarmHandlers.forEach(fn=>fn({name:Billing.EXPIRY})),get level(){return level;}};
}
test('sandbox worker ignores legacy tester flags and rejects account operations from ChatGPT pages',async()=>{const w=worker();assert.equal((await w.send('read')).access.premium,false);assert.equal(w.level,'TRUSTED_CONTEXTS');assert.equal((await w.send('tester-preview',{enabled:true})).ok,false);for(const kind of ['billing-start','billing-refresh','billing-disconnect','billing-status','open-account'])assert.equal((await w.send(kind,{},'https://chatgpt.com/c/test')).ok,false);assert.equal(w.requests.length,0);});
test('connection requires explicit optional permission and preserves the protected account page role',async()=>{const w=worker();assert.equal((await w.send('billing-start')).ok,false);assert.equal(w.requests.length,0);w.permit();const r=await w.send('billing-start',{},'account.html');assert.equal(r.ok,true);assert.equal(w.opened.at(-1),'https://www.chatdrobe.com/account/#link=ABCDE-12345-ABCDE-12345');assert.equal((await w.send('read',{},'account.html')).ok,false);assert.equal((await w.send('billing-status',{},'account.html')).ok,true);});
test('selected Living world applies only after signed device-bound Plus and never enables motion',async()=>{const w=worker();await w.send('open-upgrade',{world:'bridge',target:{theme:'bridge',livingEnabled:true,livingWorld:'starship',livingMotion:true}});assert.equal((await w.send('read')).state.prefs.livingEnabled,false);w.permit();await w.send('billing-start');w.link();await w.send('billing-refresh');assert.equal((await w.send('read')).state.prefs.livingEnabled,false);w.plus();await w.send('billing-refresh');const r=await w.send('read');assert.equal(r.access.premium,true);assert.equal(r.access.testerPreview,false);assert.equal(r.state.prefs.livingWorld,'starship');assert.equal(r.state.prefs.livingEnabled,true);assert.equal(r.state.prefs.livingMotion,false);assert.equal(r.state.prefs.livingReactions,false);assert.equal(w.data['chatdrobe:pending-upgrade-v1'],null);const pub=await w.send('read-prefs',{},'https://chatgpt.com/c/test');assert.equal(pub.state,undefined);assert.ok(!JSON.stringify(pub).includes('PRIVATE NOTE'));assert.ok(!JSON.stringify(pub).includes('member@example.test'));assert.equal(pub.snapshot.prefs.livingEnabled,true);});
test('expiry and cancellation restore effective Free state while notes and saved preferences survive',async()=>{const w=worker();w.permit();await w.send('open-upgrade',{world:'starlit'});await w.send('billing-start');w.link();w.plus();await w.send('billing-refresh');assert.equal((await w.send('read')).state.prefs.theme,'starlit');w.advance(601000);w.expire();const r=await w.send('read-prefs',{},'https://chatgpt.com/c/test');assert.equal(r.snapshot.prefs.theme,'mooncat');assert.equal(w.data.mooddock.notes,'PRIVATE NOTE');assert.equal(w.data.mooddock.prefs.theme,'starlit');w.free();await w.send('billing-refresh');assert.equal((await w.send('read')).access.premium,false);await w.send('billing-disconnect');assert.equal(w.data.mooddock.notes,'PRIVATE NOTE');assert.equal(w.data[Billing.KEY].secret,undefined);});

test('signed admin Premium is complimentary and not counted as a Stripe test payment',async()=>{const w=worker();w.permit();await w.send('billing-start');w.link();w.admin();const result=await w.send('billing-refresh');assert.equal(result.billing.premium,true);assert.equal(result.billing.adminPremium,true);assert.equal(result.billing.testSubscription,false);assert.equal(result.billing.paid,false);});
test('a linked admin selects a Premium world directly, without an upgrade or connection tab',async()=>{const w=worker();w.permit();await w.send('billing-start');w.link();w.admin();await w.send('billing-refresh');const opened=w.opened.length,requests=w.requests.length;const result=await w.send('open-upgrade',{world:'starlit'});assert.equal(result.applied,true);assert.equal(result.state.prefs.theme,'starlit');assert.equal(w.opened.length,opened);assert.equal(w.requests.length,requests);assert.equal(w.data['chatdrobe:pending-upgrade-v1'],null);});
test('stale Free state is refreshed before deciding an administrator must upgrade',async()=>{const w=worker();w.permit();await w.send('billing-start');w.link();await w.send('billing-refresh');w.admin();const opened=w.opened.length;const result=await w.send('open-upgrade',{world:'reactor'});assert.equal(result.applied,true);assert.equal(result.access.adminPremium,true);assert.equal(w.opened.length,opened);});
test('an expired cached proof refreshes and applies the Living world without a paywall',async()=>{const w=worker();w.permit();await w.send('billing-start');w.link();w.plus();await w.send('billing-refresh');w.advance(601000);const opened=w.opened.length;const result=await w.send('open-upgrade',{target:{livingEnabled:true,livingWorld:'tokyo'}});assert.equal(result.applied,true);assert.equal(result.state.prefs.livingEnabled,true);assert.equal(result.state.prefs.livingMotion,false);assert.equal(w.opened.length,opened);});
test('demotion or cancellation is enforced on a refreshed selection without deleting notes',async()=>{const w=worker();w.permit();await w.send('billing-start');w.link();w.admin();await w.send('billing-refresh');w.free();w.advance(61000);const result=await w.send('open-upgrade',{world:'starlit'});assert.equal(result.applied,false);assert.ok(w.opened.at(-1).endsWith('/account.html'));assert.ok(!w.opened.at(-1).includes('upgrade.html'));assert.equal((await w.send('read')).access.premium,false);assert.equal(w.data.mooddock.notes,'PRIVATE NOTE');});

test('approval button reopens the SAME code link without starting or revoking a connection',async()=>{const w=worker();w.permit();await w.send('billing-start',{},'account.html');const count=w.requests.length;const r=await w.send('billing-website',{},'account.html');assert.equal(r.ok,true);assert.equal(w.requests.length,count);assert.match(w.opened.at(-1),/#link=ABCDE-12345-ABCDE-12345$/);});
test('Open ChatGPT refuses unverified access and untrusted page messages',async()=>{const w=worker();const before=w.opened.length;const r=await w.send('billing-return',{},'account.html');assert.equal(r.ok,false);assert.equal(w.opened.length,before);assert.equal(w.activated.length,0);assert.equal((await w.send('billing-return',{},'https://chatgpt.com/c/test')).ok,false);});
test('Open ChatGPT applies the pending Premium world before focusing a tab or opening the homepage',async()=>{for(const existing of [true,false]){const w=worker({existing});w.permit();await w.send('open-upgrade',{world:'starlit'});await w.send('billing-start');w.link();w.admin();const r=await w.send('billing-return',{},'account.html');assert.equal(r.ok,true);assert.equal((await w.send('read')).state.prefs.theme,'starlit');assert.equal(w.data.mooddock.notes,'PRIVATE NOTE');if(existing){assert.equal(w.activated.at(-1).id,1);assert.equal(w.activated.at(-1).active,true);}else assert.equal(w.opened.at(-1),'https://chatgpt.com/');}});
