const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const P=require('../extension/prefs.js'),C=require('../extension/core.js'),A=require('../extension/access.js');
const E=path.join(__dirname,'../extension');
const load=async()=>import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(path.join(E,'world-routines.js'),'utf8')).toString('base64'));
test('new starters are Free without weakening Premium motion gating',()=>{
 for(const id of ['rally','bridge','observatory']){assert.equal(C.themeById(id).plan,'free');assert.equal(P.prefs({theme:id}).theme,id);assert.equal(A.requiresPremium({theme:id}),false);assert.equal(A.requiresPremium({theme:id,idleMode:'stroll'}),true);assert.equal(A.effective(P.prefs({theme:id,idleMode:'stroll'}),{premium:false}).idleMode,'off');}
});
test('fresh installations start both workspace and side panel light, explicit preferences survive',()=>{assert.equal(P.DEFAULTS.mode,'light');assert.equal(P.DEFAULTS.panelMode,'light');assert.equal(C.state().prefs.mode,'light');for(const mode of ['chatgpt','system','theme','light','dark'])assert.equal(C.state({prefs:{mode}}).prefs.mode,mode);assert.equal(C.state({prefs:{panelMode:'dark'}}).prefs.panelMode,'dark');});
test('new appearance files preserve visual motion without authorizing text inspection or payment',()=>{
 for(const theme of ['rally','bridge','observatory']){const v=C.importAppearance(JSON.stringify({format:'chatdrobe-appearance',version:1,prefs:{theme,mode:'dark',idleMode:'stroll',wordBitesConsent:true,isPro:true}}));assert.equal(v.theme,theme);assert.equal(v.mode,'dark');assert.equal(v.idleMode,'stroll');assert.equal(v.wordBitesConsent,false);assert.equal(v.isPro,undefined);}
});
test('routine module is lazy and manifest exposes only local files',()=>{const m=require('../extension/manifest.json');assert.ok(!m.content_scripts[0].js.includes('world-routines.js'));for(const f of m.web_accessible_resources[0].resources)assert.ok(fs.existsSync(path.join(E,f)));assert.deepEqual(m.permissions,['storage','sidePanel','alarms']);assert.deepEqual(m.host_permissions,['https://chatgpt.com/*']);});
test('three different routine families use no network, history scan or continuous JS loop',async()=>{const src=fs.readFileSync(path.join(E,'world-routines.js'),'utf8');assert.ok(!/fetch\(|setInterval\(|requestAnimationFrame\(|\.innerHTML|\.textContent|\.innerText|createTreeWalker/.test(src.replace('sheet.textContent','sheetStyles')));const m=await load();assert.deepEqual(m.WORLD_IDS,['rally','bridge','observatory']);});
function geometry({width=1440,formLeft=400,formRight=1250,blocked=false,top=850}={}){
 const main={left:210,right:width,width:width-210},form={left:formLeft,right:formRight,width:formRight-formLeft,top};
 return {doc:{querySelector:()=>({getBoundingClientRect:()=>main}),getElementById:()=>({closest:()=>({getBoundingClientRect:()=>form})}),elementFromPoint:()=>({closest:()=>blocked?{}:null})},win:{innerWidth:width,innerHeight:1040},form};
}
test('stages fit clear margins and remain above the composer',async()=>{const m=await load();const {doc,win,form}=geometry();const b=m.marginStage(doc,win);assert.ok(b);assert.ok(b.x>form.right||b.x+b.width<form.left);assert.ok(b.y+b.height<form.top);assert.ok(b.x>=0&&b.x+b.width<=win.innerWidth);});
test('narrow pages, covered margins and absent composer safely suppress routines',async()=>{const m=await load();for(const opts of [{width:900,formLeft:240,formRight:870},{blocked:true},{top:120}]){const {doc,win}=geometry(opts);assert.equal(m.marginStage(doc,win),null);}assert.equal(m.marginStage({querySelector:()=>null,getElementById:()=>null},{innerWidth:1440}),null);});
test('existing notes, shortcuts, prompts and named workspaces survive a new-world switch',()=>{const start=C.state({notes:'keep me',prompts:[{id:'p',title:'Example',body:'private'}],bookmarks:[{id:'b',title:'Chat',url:'https://chatgpt.com/c/123'}],presets:[{id:'s',name:'My desk',prefs:{theme:'mooncat',mode:'dark'}}]});const next=C.reduce(start,{type:'settings',value:{theme:'rally'}});for(const k of ['notes','prompts','bookmarks','presets'])assert.deepEqual(next[k],start[k]);});
