import {createScene,SCENE_CSS} from './living/quiet-scene.mjs';
import {worldById} from './living/model.mjs';
import {CLIPS,CLIP_LABELS} from './living/companion-motion.mjs';
const $=id=>document.getElementById(id),host=$('scene'),shadow=host.attachShadow({mode:'open'}),style=new CSSStyleSheet();style.replaceSync(SCENE_CSS);shadow.adoptedStyleSheets=[style];
let scene=null,serial=0,playing=false,selected='groom';const reduced=matchMedia('(prefers-reduced-motion: reduce)');
function stop(){playing=false;paint();}
function paint(){if(!scene)return;$('scene-shell').classList.toggle('closeup',$('closeup').checked);scene.update({world:$('world').value,light:$('night').checked?'night':'day',weather:$('world').value==='tokyo'?'rain':'clear',motion:playing&&!reduced.matches,active:!document.hidden,idleStage:'unwinding',pose:playing?selected:'rest',poseSerial:serial,busy:false,stage:0,quiet:false});$('play').disabled=reduced.matches;$('status').textContent=reduced.matches?'Reduced motion is enabled. Scrub the slider to inspect a still pose.':playing?CLIP_LABELS[selected]+' · finite, one-shot performance.':'Motion off. Choose an action and press Play.';if($('closeup').checked){const habitat=shadow.querySelector('.companion-habitat');if(habitat){habitat.style.width='96%';habitat.style.left='2%';habitat.style.bottom='3%';}}else scene.setHabitat({view:'portal',width:250,left:0});}
function mount(){scene?.dispose();scene?.element.remove();scene=createScene(document,worldById($('world').value));shadow.append(scene.element);const options=$('world').value==='starship'?['inspect','calibrate','dock']:['blink','look','ears','breathe','groom','scratch','stretch','knead','yawn','curl'];$('action').replaceChildren(...options.map(value=>{const o=document.createElement('option');o.value=value;o.textContent=CLIP_LABELS[value];return o;}));selected=options.includes(selected)?selected:options[0];$('action').value=selected;playing=false;paint();}
$('world').addEventListener('change',mount);$('action').addEventListener('change',()=>{selected=$('action').value;stop();});$('play').addEventListener('click',()=>{serial++;playing=true;paint();});$('stop').addEventListener('click',stop);
$('scrub').addEventListener('input',()=>{playing=false;paint();scene.previewPose(selected,Number($('scrub').value)/100);$('status').textContent=CLIP_LABELS[selected]+' · pose at '+$('scrub').value+'% (still).';});
for(const id of ['closeup','night'])$(id).addEventListener('change',paint);
for(const button of document.querySelectorAll('[data-stage]'))button.addEventListener('click',()=>{if($('world').value==='starship')return;selected=button.dataset.stage;$('action').value=selected;serial++;playing=true;paint();});
reduced.addEventListener('change',stop);document.addEventListener('visibilitychange',stop);window.addEventListener('pagehide',()=>scene?.dispose());mount();
