const EXPECTED={chatdrobe_accounts:{id:'uuid',email:'text',billing_id:'text',role:'text',verified_at:'timestamp with time zone',created_at:'timestamp with time zone',last_login_at:'timestamp with time zone',accepted_beta_at:'timestamp with time zone'},chatdrobe_login_challenges:{nonce_hash:'text',code_hash:'text',email:'text',mode:'text',attempts:'integer',expires_at:'timestamp with time zone'},chatdrobe_sessions:{token_hash:'text',account_id:'uuid',authenticated_at:'timestamp with time zone',expires_at:'timestamp with time zone'},chatdrobe_admin_invites:{email_hash:'text'},chatdrobe_account_audit:{id:'bigint',action:'text',created_at:'timestamp with time zone'},chatdrobe_app_settings:{key:'text',value:'jsonb',updated_at:'timestamp with time zone'}};
export async function accountSchemaReady(client){
 const names=Object.keys(EXPECTED),result=await client.query(`SELECT c.relname,a.attname,format_type(a.atttypid,a.atttypmod) AS type,a.attnotnull FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid WHERE n.nspname='public' AND c.relkind='r' AND c.relname=ANY($1::text[]) AND a.attnum>0 AND NOT a.attisdropped`,[names]);
 for(const[table,columns]of Object.entries(EXPECTED))for(const[column,type]of Object.entries(columns))if(!result.rows.some(r=>r.relname===table&&r.attname===column&&r.type===type&&r.attnotnull))return false;
 const constraints=(await client.query(`SELECT c.relname,k.contype,pg_get_constraintdef(k.oid) AS definition FROM pg_catalog.pg_constraint k JOIN pg_catalog.pg_class c ON c.oid=k.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname=ANY($1::text[])`,[names])).rows;
 const keys={chatdrobe_accounts:'id',chatdrobe_login_challenges:'nonce_hash',chatdrobe_sessions:'token_hash',chatdrobe_admin_invites:'email_hash',chatdrobe_account_audit:'id',chatdrobe_app_settings:'key'};
 for(const[table,key]of Object.entries(keys))if(!constraints.some(r=>r.relname===table&&r.contype==='p'&&r.definition===`PRIMARY KEY (${key})`))return false;
 for(const col of ['email','billing_id'])if(!constraints.some(r=>r.relname==='chatdrobe_accounts'&&r.contype==='u'&&r.definition===`UNIQUE (${col})`))return false;
 if(!constraints.some(r=>r.relname==='chatdrobe_sessions'&&r.contype==='f'&&/FOREIGN KEY \(account_id\) REFERENCES (public\.)?chatdrobe_accounts\(id\)/.test(r.definition)))return false;
 const setting=(await client.query("SELECT value FROM public.chatdrobe_app_settings WHERE key='test_checkout'")).rows[0];return typeof setting?.value==='boolean';
}
