import {linkFragment} from './connection-flow.js';
/* Same-origin cookie-authenticated UI. Credentials never enter localStorage or URLs. */
const page=document.querySelector('[data-account-page]');
if(page){
 const $=s=>page.querySelector(s),mode=page.dataset.accountPage,message=$('[data-account-message]');let profile=null,adminPage=1,loading=false;
 const text=(n,v)=>{if(n)n.textContent=v;};function note(value,error=false){text(message,value);message.dataset.error=String(error);}
 async function call(action,input,endpoint='account'){
  const response=await fetch('/api/'+endpoint+'?action='+action,{method:input===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',redirect:'error',headers:input===undefined?{}:{'Content-Type':'application/json','X-ChatDrobe-Request':'account-v1'},body:input===undefined?undefined:JSON.stringify(input)});
  let result;try{result=await response.json();}catch{throw new Error('The account service did not return a valid response. Please retry.');}if(!response.ok){const e=new Error(result.error?.message||'Request could not be completed.');e.code=result.error?.code;e.status=response.status;throw e;}return result;
 }
 const date=value=>{if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString();};
 const busy=async(fn)=>{if(loading)return;loading=true;page.setAttribute('aria-busy','true');try{await fn();}catch(e){note(e.message,true);}finally{loading=false;page.removeAttribute('aria-busy');}};
 function signedOut(){profile=null;$('[data-account-content]')?.setAttribute('hidden','');$('[data-admin-content]')?.setAttribute('hidden','');$('[data-admin-users]')?.replaceChildren();text($('[data-account-email]'),'');$('[data-account-signedout]')?.removeAttribute('hidden');}
 const destination=()=>['admin','account'].includes(new URLSearchParams(location.search).get('next'))?'/'+new URLSearchParams(location.search).get('next')+'/':'/account/';
 if(mode==='signup'||mode==='signin'){
  const emailForm=$('[data-auth-email]'),codeForm=$('[data-auth-code]');busy(async()=>{const status=await call('status');if(!status.signInAvailable){note('Email sign-in is not connected yet. No code will be sent until setup is complete.');return;}emailForm.hidden=false;note('Enter your email to receive a one-time code.');});
  emailForm.addEventListener('submit',event=>{event.preventDefault();busy(async()=>{const input={email:emailForm.elements.email.value,mode};if(mode==='signup')input.acceptBeta=emailForm.elements.acceptBeta.checked;note('Sending your verification code…');const reply=await call('request-code',input);emailForm.hidden=true;codeForm.hidden=false;note(reply.message);codeForm.elements.code.focus();});});
  codeForm.addEventListener('submit',event=>{event.preventDefault();busy(async()=>{note('Verifying your code…');await call('verify-code',{code:codeForm.elements.code.value.trim()});codeForm.reset();location.assign(destination()+linkFragment(location.hash));});});
  $('[data-auth-again]').addEventListener('click',()=>{codeForm.reset();codeForm.hidden=true;emailForm.hidden=false;note('Enter your email and request a fresh code.');emailForm.elements.email.focus();});
 }else{
  async function refreshProfile(){try{profile=await call('me');$('[data-account-signedout]').hidden=true;}catch(e){if(e.status===401||e.status===403){signedOut();note(e.message,true);return false;}throw e;}return true;}
  async function showAccount(){if(!await refreshProfile())return;const{user,subscription,payments}=profile;$('[data-account-content]').hidden=false;text($('[data-account-email]'),user.email);text($('[data-account-plan]'),subscription.plan==='test_plus'?'Test Plus — no live charge':'Free');text($('[data-account-subscription]'),`Subscription: ${subscription.status.replaceAll('_',' ')}${subscription.paidUntil?' · paid through '+date(subscription.paidUntil*1000):''}${subscription.cancelAtPeriodEnd?' · cancellation scheduled':''}`);text($('[data-account-billing-note]'),payments.enabled?'Stripe sandbox is available. Test cards only; no real money is collected.':'Test checkout is not active yet. Your Free account remains available.');$('[data-account-checkout]').disabled=!payments.enabled||!['free','canceled','incomplete_expired'].includes(subscription.status);$('[data-account-portal]').disabled=subscription.status==='free';$('[data-account-admin]').hidden=user.role!=='admin';note('Signed in. Your subscription belongs to this account, not a browser folder.');}
  function approvedLocation(value,host){const u=new URL(value);if(u.protocol!=='https:'||u.hostname!==host||u.username||u.password||u.port)throw new Error('Unexpected payment destination.');return u.href;}
  if(mode==='account'){
   busy(showAccount);
   $('[data-account-checkout]').addEventListener('click',()=>busy(async()=>{note('Opening Stripe test checkout…');const r=await call('checkout',{},'billing');location.assign(approvedLocation(r.url,'checkout.stripe.com'));}));
   $('[data-account-portal]').addEventListener('click',()=>busy(async()=>{const r=await call('portal',{},'billing');location.assign(approvedLocation(r.url,'billing.stripe.com'));}));
   $('[data-account-refresh]').addEventListener('click',()=>busy(async()=>{try{await call('entitlement',{},'billing');}catch(e){if(e.code!=='BILLING_DISABLED')throw e;}await showAccount();}));
   $('[data-account-signout]').addEventListener('click',()=>busy(async()=>{await call('signout',{});signedOut();note('Signed out.');}));
   $('[data-account-signout-all]').addEventListener('click',()=>{if(confirm('Sign out this account from every browser? Local extension notes are unchanged.'))busy(async()=>{await call('signout-all',{});signedOut();note('Signed out of all browsers.');});});
  }
  if(mode==='admin'){
   const labels={emailDelivery:'Verified sender / email API',database:'Database connection setting',testSecret:'Stripe test secret',webhookSecret:'Webhook signing secret',price:'Annual test price',signingKey:'Server access-signing key',webhookEndpoint:'Webhook endpoint ID',portal:'Billing portal configuration',testMode:'Test billing mode',origin:'Canonical billing origin'};
   async function setup(){const state=await call('admin-setup'),list=$('[data-admin-checks]');list.replaceChildren();for(const[key,value]of Object.entries(state.checks||{})){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=labels[key]||key;dd.textContent=value?'Configured':'Missing';dd.dataset.ready=String(value);list.append(dt,dd);}text($('[data-admin-payment-state]'),state.enabled?'New test checkouts are enabled. Provider objects are checked before checkout; real webhook delivery must still be tested.':state.ready?'Configuration is present. You can verify provider settings and enable test checkout.':'Configuration is incomplete. Add the missing server environment settings; no payment is collected.');$('[data-admin-enable]').disabled=!state.ready||state.enabled;$('[data-admin-disable]').disabled=!state.enabled;}
   async function listUsers(){const form=$('[data-admin-filters]'),result=await call('admin-users',{page:adminPage,q:form.elements.q.value,plan:form.elements.plan.value}),body=$('[data-admin-users]');body.replaceChildren();for(const row of result.users){const tr=document.createElement('tr');for(const value of [row.email,row.plan==='test_plus'?'Test Plus':'Free',row.role+(row.disabled_at?' (disabled)':''),row.subscription_status,date(row.created_at),date(row.last_login_at)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}body.append(tr);}for(const[k,v]of Object.entries(result.counts))text($(`[data-metric="${k}"]`),String(v));text($('[data-admin-coverage]'),result.coverage);text($('[data-admin-page]'),`Page ${result.page} · ${result.total} matching accounts`);$('[data-admin-empty]').hidden=result.users.length!==0;$('[data-admin-prev]').disabled=result.page<=1;$('[data-admin-next]').disabled=result.page*result.pageSize>=result.total;}
   busy(async()=>{if(!await refreshProfile())return;if(profile.user.role!=='admin'){signedOut();note('This account does not have administrator access.',true);return;}$('[data-admin-content]').hidden=false;await Promise.all([listUsers(),setup()]);note('Administrator session verified. Test subscriptions are shown separately from live paid accounts.');});
   $('[data-admin-filters]').addEventListener('submit',e=>{e.preventDefault();adminPage=1;busy(listUsers);});$('[data-admin-prev]').addEventListener('click',()=>{adminPage=Math.max(1,adminPage-1);busy(listUsers);});$('[data-admin-next]').addEventListener('click',()=>{adminPage++;busy(listUsers);});$('[data-admin-setup-refresh]').addEventListener('click',()=>busy(setup));
   for(const[selector,enabled]of [['[data-admin-enable]',true],['[data-admin-disable]',false]])$(selector).addEventListener('click',()=>{if(confirm(enabled?'Enable Stripe test checkout? This uses test cards only and never collects real money.':'Pause new test checkouts? Existing subscription verification and cancellation remain available.'))busy(async()=>{await call('admin-activate',{enabled});await setup();note(enabled?'Test checkout enabled. Complete a real Stripe sandbox transaction before calling the flow verified.':'New test checkouts paused.');});});
  }
 }
}
