import {linkCode as readLinkCode,linkFragment,authLink} from './connection-flow.js';
/* Owner login and explicit pairing. Codes remain in fragments, not server logs or payment metadata. */
const root=document.querySelector('[data-account-page]');
if(root){
 const page=root.dataset.accountPage;
 const linkCode=()=>readLinkCode(location.hash);
 const fragment=()=>linkFragment(location.hash);
 for(const anchor of root.querySelectorAll('a[href]')){const path=anchor.getAttribute('href');if(['/signin/','/signup/'].includes(path))anchor.setAttribute('href',authLink(path,location.search,location.hash));}
 function node(tag,text,attrs={}){const n=document.createElement(tag);if(text)n.textContent=text;for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;}
 async function api(action,value){let r;try{r=await fetch('/api/account?action='+action,{method:value===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',redirect:'error',headers:value===undefined?{}:{'Content-Type':'application/json','X-ChatDrobe-Request':'account-v1'},body:value===undefined?undefined:JSON.stringify(value)});}catch{throw Error('Could not reach ChatDrobe. Retry here; do not generate another code or purchase again.');}const v=await r.json();if(!r.ok)throw Error(v.error?.message||'Account request failed.');return v;}
 if(page==='signin'||page==='signup'){
  const box=node('section','',{class:'account-card'}),title=node('h2','Owner login'),notice=node('p','Sign in once. Your account is remembered for up to 30 days. Administrators receive complimentary Premium; no purchase is required.'),status=node('p','Checking owner login…',{role:'status'});
  const form=node('form'),email=node('input','',{type:'email',name:'email',autocomplete:'username',required:'',maxlength:'254',id:'owner-email'}),password=node('input','',{type:'password',name:'password',autocomplete:'current-password',required:'',maxlength:'128',id:'owner-password'}),button=node('button','Sign in as owner',{type:'submit',class:'btn'});
  form.append(node('label','Owner email',{for:'owner-email'}),email,node('label','Owner password',{for:'owner-password'}),password,button);form.hidden=true;box.append(title,notice,status,form);root.append(box);
  if(linkCode())notice.append(document.createTextNode(' Your extension code is already attached. After signing in, compare the displayed code and approve the connection—no copying needed.'));
  api('status').then(v=>{form.hidden=!v.ownerLoginAvailable;status.textContent=v.ownerLoginAvailable?'Use the owner credentials configured in Vercel. Administrative actions may require a fresh sign-in.':'Set ADMIN_EMAIL and ADMIN_PASSWORD_HASH in Vercel, then redeploy. Public email signup is separate.';}).catch(()=>{status.textContent='Unable to check owner login.';});
  let busy=false;form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;button.disabled=true;try{await api('owner-login',{email:email.value,password:password.value});password.value='';const next=new URLSearchParams(location.search).get('next');location.assign((next==='admin'?'/admin/':'/account/')+fragment());}catch(err){status.textContent=err.message;password.value='';}finally{busy=false;button.disabled=false;}});
 }
 if(page==='admin')root.append(node('p','Administrative data and controls require a sign-in within the last 15 minutes. '),node('a','Reauthenticate administrator',{href:'/signin/?next=admin'}));
 if(page==='account'){
  const card=node('section','',{class:'account-card'}),status=node('p','',{role:'status'}),form=node('form'),input=node('input','',{id:'extension-link-code',name:'code',maxlength:'23',autocomplete:'off',required:''}),confirm=node('input','',{type:'checkbox',required:'',id:'link-confirm'}),button=node('button','Connect this extension',{type:'submit',class:'btn'}),list=node('div');
  input.value=linkCode();const label=node('label',null,{class:'account-check'});label.append(confirm,node('span','I started this connection in my own ChatDrobe extension, and both codes match.'));
  form.append(node('p',linkCode()?'Your code is already filled in. Check that it matches your extension, tick the confirmation, and click Connect this extension.':'Open the approval link in the ChatDrobe extension to fill this code automatically. You may also paste the current code below.'),node('label','Code shown in your extension',{for:'extension-link-code'}),input,label,button);
  card.append(node('h2','Connected extensions'),node('p','Connect once → verify Premium → open ChatGPT. Your connection is remembered for up to 30 days; Premium is checked regularly. Administrators do not need checkout.'),status,form,list);card.hidden=true;root.append(card);
  const signedOut=root.querySelector('[data-account-signedout]');if(signedOut){const login=signedOut.querySelector('a[href*="signin"]');if(login)login.href='/signin/?next=account'+fragment();}
  const content=root.querySelector('[data-account-content]');
  if(content)new MutationObserver(()=>{if(content.hidden){card.hidden=true;list.replaceChildren();status.textContent='';}}).observe(content,{attributes:true,attributeFilter:['hidden']});
  async function showDevices(){const result=await api('devices');list.replaceChildren(node('h3','Your linked installations'));if(!result.devices.length)list.append(node('p','No extensions linked yet.'));
   for(const device of result.devices){const row=node('p',`Extension ${device.extension_id.slice(0,8)}… · connected until ${new Date(device.expires_at).toLocaleDateString()} `),remove=node('button','Disconnect',{type:'button',class:'plain'});remove.addEventListener('click',async()=>{if(!window.confirm('Disconnect this installation? Cached access expires within ten minutes. Local notes remain unchanged.'))return;remove.disabled=true;try{await api('revoke-device',{deviceId:device.id});await showDevices();window.dispatchEvent(new CustomEvent('chatdrobe:link-approved',{detail:{approved:false}}));}catch(e){status.textContent=e.message;remove.disabled=false;}});row.append(remove);list.append(row);}
  }
  api('me').then(v=>{if(!v.extensionLinkingAvailable)return;card.hidden=false;const notice=content?.querySelector('.notice-box');if(notice)notice.textContent='Use extension v__EXTENSION_VERSION__. In Worlds, choose motion, select a world and use Check display. Admin Premium is complimentary; Stripe test subscriptions do not move real money.';return showDevices();}).catch(()=>{});
  let busy=false;form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;button.disabled=true;try{await api('link-extension',{code:input.value,confirmed:confirm.checked});history.replaceState(null,'',location.pathname+location.search);input.value='';confirm.checked=false;form.hidden=true;status.textContent='Connection approved. Return to the extension to check signed access and the selected world’s page status. Approval here does not confirm that the scene is visible.';await showDevices();window.dispatchEvent(new CustomEvent('chatdrobe:link-approved',{detail:{approved:true}}));}catch(err){status.textContent=err.message;}finally{busy=false;button.disabled=false;}});
 }
}
