import {escape} from './render.mjs';
import {explorerContent} from './explorer.mjs';
export function enhance(html,route,themes){
 // Normalize the migrated homepage's redundant closing section; browser output is unchanged.
 html=html.replace('</div></section></section></main>','</div></section></main>');
 if(route==='/themes/'){
 const categories=[...new Set(themes.map(t=>t.label))];
 const controls=`<form id="catalog-form" class="catalog-form js-controls" role="search"><label>Search worlds<input name="q" type="search" maxlength="80" placeholder="Cat, robot, calm…" autocomplete="off"></label><label>Collection<select name="category" aria-label="Collection"><option value="">All collections</option>${categories.map(c=>`<option>${escape(c)}</option>`).join('')}</select></label><label>Appearance<select name="tone" aria-label="Appearance"><option value="">Light & dark</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Launch plan<select name="plan" aria-label="Launch plan"><option value="">All plans</option><option value="free">Free at launch</option><option value="pro">Plus preview</option></select></label><label>Sort<select name="sort" aria-label="Sort"><option value="featured">Featured</option><option value="name">Name A–Z</option></select></label><label class="check"><input name="favorites" type="checkbox"> Favorites only</label><button class="btn outline small" type="button" id="reset-catalog">Reset filters</button><button class="plain" type="button" id="clear-favorites">Clear saved favorites</button></form><noscript><p>All worlds are available below. JavaScript adds search, filters and local favorites.</p></noscript>`;
 html=html.replace('<div id="catalog-controls"></div>',controls).replace('</head>','<script type="module" src="/assets/catalog.js"></script></head>');
 }
 const theme=themes.find(t=>route==='/themes/'+t.id+'/');
 if(theme){
 const controls=`<section class="showroom js-controls"><div><p class="eyebrow">MAKE IT YOURS, BEFORE YOU INSTALL.</p><h2>Your reading rhythm.</h2><p>Try safe appearance controls. Save settings for explicit import into the extension. This is not the planned advanced scene editor.</p></div><form id="showroom-form" class="showroom-form" data-theme-id="${theme.id}"><label>Font family<select name="font" aria-label="Font family"><option value="system">System</option><option value="serif">Serif</option><option value="mono">Monospace</option></select></label><label for="look-size">Text size · <output data-value="fontSize">16</output> px<input type="range" id="look-size" name="fontSize" min="13" max="24" step="1" value="16"></label><label for="look-line">Line spacing · <output data-value="lineHeight">1.65</output><input type="range" id="look-line" name="lineHeight" min="1.3" max="2.2" step="0.05" value="1.65"></label><label for="look-width">Conversation width · <output data-value="width">850</output> px<input type="range" id="look-width" name="width" min="600" max="1400" step="50" value="850"></label><label class="check"><input type="checkbox" name="decoration" checked> Show companion</label><label class="check"><input type="checkbox" name="focus"> Focus mode</label><label class="check"><input type="checkbox" name="bubbles" checked> Conversation bubbles</label></form><div class="reading-surface" data-theme="${theme.id}"><div id="reading-sample"><strong>A little room for your next good idea.</strong><p>Start with a question. Explore it at your own pace. A comfortable reading space is yours to define.</p></div></div><p class="micro">The width illustration is scaled to fit this page; the extension uses the selected pixel value. Motion is off in every website export.</p><div class="actions"><button type="button" class="btn" id="export-look">Save custom appearance ↓</button><button type="button" class="btn outline" id="share-look">Copy look link</button><button type="button" class="plain" id="reset-look">Reset controls</button></div><label class="import-label">Import an appearance for this world<input type="file" id="import-look" accept="application/json,.json"></label><input id="share-url" aria-label="Shareable appearance link" readonly hidden></section>`;
 html=html.replace(`<div id="showroom-controls" data-theme-id="${theme.id}"></div>`,controls).replace('</head>','<script type="module" src="/assets/showroom.js"></script></head>');
 }
 if(route==='/privacy/')html=html.replace('<h2>The extension</h2>','<h2>Website favorites and shared looks</h2><p>Only when you save a favorite do we store its theme ID in localStorage under chatdrobe:favorites:v1. Use Clear saved favorites in the catalog to remove it. Favorites do not sync across devices. Shared look URLs contain only validated appearance settings, not conversation data. Imported appearance files are read locally and are not uploaded.</p><h2>The extension</h2>');
 return explorerContent(html,route,themes).replace('</head>','<link rel="stylesheet" href="/assets/experience.css"></head>');
}
