import {prices} from './render.mjs';
import {livingCollection,livingCards} from './living-collection.mjs';
const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export const premiumPreviewFeatures=[
 ...livingCollection.map(w=>({name:w.name,status:'Private beta',description:w.description})),
 {name:'Portal and Full World',status:'Private beta',description:'Choose a small scene window or surroundings around the reading column. Scenes hide when the layout has no safe space.'},
 {name:'Rally Garage cruise',status:'Private beta',description:'An opt-in car cruise, park and headlight sequence in a clear margin.'},
 {name:'Orbital Bridge drone',status:'Private beta',description:'A miniature drone can undock, inspect and recharge.'},
 {name:'Solar Observatory orbit',status:'Private beta',description:'One quiet planetary orbit when the page is idle.'},
 {name:'Word Bites',status:'Separate opt-in',description:'A text-aware experiment requiring its own local text-access permission. The three Living environments do not read conversation text.'}
];
export const plannedPlusFeatures=[
 {name:'Advanced scene editor',description:'More control over scene layers and decorative behavior.'},
 {name:'Scheduled worlds',description:'Automatic switching between your selected environments.'},
 {name:'Expanded workspace limits',description:'Additional saved-prompt and workspace capacity.'}
];
export function counts(themes){return {total:themes.length,free:themes.filter(t=>t.plan==='free').length,plus:themes.filter(t=>t.plan==='pro').length,palettes:themes.length*2};}
export function upgradeLegacyCopy(html,themes){const c=counts(themes);return html.replaceAll('All 12 worlds unlocked',`${c.free} Free worlds · Premium tester preview`).replaceAll('Explore all 12 worlds',`Explore all ${c.total} worlds`).replaceAll('12 original worlds',`${c.total} original worlds`).replaceAll('12 worlds',`${c.total} worlds`).replaceAll('8 complete original worlds',`${c.free} complete original worlds`);}
function featureCards(items){return `<div class="feature-grid product-feature-grid">${items.map(x=>`<article class="feature product-feature"><span class="tag">${esc(x.status||'Included')}</span><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p></article>`).join('')}</div>`;}
export function homeInsert(themes){const c=counts(themes);return `<section class="section wrap product-positioning"><p class="eyebrow">YOUR WORKSPACE, YOUR WAY</p><h2>One extension. A wardrobe and a world.</h2><div class="value-grid"><article><strong>${c.total}</strong><span>static themes</span></article><article><strong>${c.free}</strong><span>Free themes</span></article><article><strong>${c.plus}</strong><span>Plus themes</span></article><article><strong>${livingCollection.length}</strong><span>Plus Living environments</span></article></div><p>Use a calm, static theme or a layered Living environment. Reading controls and local tools stay useful in either view.</p><a href="/features/">See every feature ↗</a></section>`;}
export function injectHome(html,themes){const marker='<section class="band section"><div class="wrap"><div class="center"><p class="eyebrow">YOUR SPACE. YOUR CHOICE.</p>';return upgradeLegacyCopy(html.replace(marker,homeInsert(themes)+marker),themes);}
export function featuresPage(themes){const c=counts(themes);return `<section class="section wrap"><div class="page-intro"><p class="eyebrow">STATIC THEMES + LIVING ENVIRONMENTS</p><h1>A workspace that feels like your place.</h1><p>${c.total} static themes, ${livingCollection.length} Plus Living environments, and practical local tools. The ${c.free} Free themes include light/dark appearance and reading controls.</p></div>${livingCards('features')}<section class="feature-section"><h2>Free essentials</h2>${featureCards([
 {name:`${c.free} Free worlds`,description:'Cozy cats, cars, spaceships, nature, code and calm palettes.'},
 {name:'Reading controls',description:'Adjust font, line spacing and conversation width. Keep the composer and native disclaimer readable.'},
 {name:'Local workspace tools',description:'Reusable prompts, notes, a focus timer and saved appearance workspaces. Notes and prompts stay in the browser profile; no automatic sending.'}
 ])}</section><section class="feature-section premium-band"><h2>Plus, in the private extension build</h2>${featureCards(premiumPreviewFeatures)}</section><section class="feature-section"><p class="eyebrow">PLANNED · NOT INCLUDED TODAY</p><h2>Further down the track</h2>${featureCards(plannedPlusFeatures.map(x=>({...x,status:'Planned'})))}</section><div class="actions"><a class="btn" href="/pricing/">Compare Free &amp; Plus</a><a href="/living-worlds/">Explore Living Worlds</a></div></section>`;}
export function premiumPage(themes){const c=counts(themes);return `<section class="section wrap"><div class="page-intro"><p class="eyebrow">CHATDROBE PLUS</p><h1>More than a theme.<br>A place to be.</h1><p>A rainy city loft, a starship viewport and a comfortable train carriage. Plus includes all ${c.total} static themes and three Living environments, with atmosphere, focus journeys and optional companions.</p><div class="actions"><a class="btn" href="/living-worlds/">Explore the Living Worlds ↗</a><a href="/pricing/">Plus · $29/year</a></div><p class="micro">Private beta access is available in the extension. Checkout is not enabled yet.</p></div>${livingCards('premium')}<div class="notice-box"><h2>They are already in the test build.</h2><p>Using extension 0.5.0 or later? Open <strong>About → Enable private tester preview → Living</strong>, choose a world, and select <strong>Enter world</strong>. Use Full World for surroundings or Portal for a smaller window.</p><a href="/install/#living">Setup instructions ↗</a></div><section class="feature-section"><h2>Atmosphere without losing your place</h2><p>Choose day or night, world-specific weather and a focus journey. Motion and activity reactions are optional. These environments do not inspect conversation text; they pause or hide when the layout or user settings require it.</p></section><section class="feature-section"><h2>${c.plus} additional static themes</h2><div class="premium-world-list">${themes.filter(t=>t.plan==='pro').map(t=>`<a href="/themes/${t.id}/"><strong>${esc(t.name)}</strong><span>${esc(t.label)}</span><small>${esc(t.description)}</small></a>`).join('')}</div></section><section class="feature-section"><p class="eyebrow">FUTURE DEVELOPMENT · NOT PART OF TODAY’S OFFER</p>${featureCards(plannedPlusFeatures.map(x=>({...x,status:'Planned'})))}</section><div class="notice-box"><strong>Checkout is not enabled yet.</strong><p>The billing API is reachable, but paid activation, subscriber sign-in and the full payment flow are still being completed. The current private tester preview is not a paid subscription.</p></div></section>`;}
export function pricingPage(themes,config){const c=counts(themes);const rows=[
 ['Static themes',`${c.free} Free themes`,`${c.total} themes, including ${c.plus} Plus themes`],
 ['Living environments','—','Rainy Tokyo Loft · Starship Journey · Cozy Train Journey'],
 ['Light/dark and reading controls','Included','Included'],
 ['Local prompts, notes and timer','Included','Included'],
 ['Portal and Full World','—','Included in private beta'],
 ['Weather, lighting and focus journeys','—','Included in private beta'],
 ['Optional ambient routines','—','Included in private beta'],
 ['Word Bites','—','Separate text-access opt-in']
 ];return `<section class="section wrap"><div class="page-intro"><p class="eyebrow">FREE OR PLUS</p><h1>Your everyday workspace.<br>Your extraordinary surroundings.</h1><p>Start with comfortable reading and original Free themes. Choose Plus for the complete static collection and three Living environments.</p></div>${prices(config,themes)}<div class="table-wrap feature-compare"><table><caption>Current private-build features. Paid checkout is not enabled yet.</caption><thead><tr><th scope="col">Feature</th><th scope="col">Free</th><th scope="col">Plus</th></tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">${esc(r[0])}</th><td>${esc(r[1])}</td><td>${esc(r[2])}</td></tr>`).join('')}</tbody></table></div><div class="notice-box"><strong>Plus is $${esc(config.plusAnnualUsd)}/year. Checkout is not enabled yet.</strong><p>No payment is being collected in this beta. Testing access is enabled explicitly in the extension. An annual price does not activate a subscription or grant access by itself.</p><p>Advanced scene editing, scheduled worlds, Robot Colony and World Studio are not included in the current feature list.</p></div><div class="actions"><a href="/features/">See all features ↗</a><a href="/living-worlds/">Meet the Living Worlds ↗</a></div></section>`;}
export function marketingPage(){return `<section class="section wrap"><div class="page-intro"><p class="eyebrow">LAUNCH POSITIONING</p><h1>Lead with a place.<br>Keep people with the product.</h1><p>Show Rainy Tokyo Loft, Starship Journey and Cozy Train Journey first. Then demonstrate readable conversations, a clear composer and useful local tools.</p></div><div class="feature-grid"><article class="feature"><h2>Discover</h2><p>A visual world reveal leads to its Living Worlds page.</p></article><article class="feature"><h2>Try</h2><p>Free static themes and private-beta setup let people understand the product without payment.</p></article><article class="feature"><h2>Choose Plus</h2><p>$29/year for the complete collection and Living environments. Checkout remains disabled until subscriber access is verified.</p></article></div><p class="notice-box">Do not advertise future concepts as delivered features, or promise launch dates before the payment and installation checks pass.</p></section>`;}
