import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {email,secret,validSecret,hash,codeDigest,sameHash,webConfig,COOKIE,CHALLENGE_COOKIE,cookieValue,setCookie,requireOrigin,requireAdmin,subscriptionSummary,AccountError} from '../accounts-policy.mjs';
import {createAccountHandler} from '../accounts-http.mjs';import {codeMailer} from '../email-delivery.mjs';import {accountService} from '../accounts-service.mjs';
const config=webConfig({RESEND_API_KEY:'re_'+'x'.repeat(24),AUTH_EMAIL_FROM:'ChatDrobe <login@chatdrobe.com>'});
test('email identity is normalized without guessing provider aliases',()=>{assert.equal(email(' User.Name+tag@Example.com '),'user.name+tag@example.com');for(const v of ['name','a\r\nb@example.com','a@b','a..b@example.com','x'.repeat(300)+'@example.com',null])assert.throws(()=>email(v));});
test('credentials are canonical 256-bit secrets; OTP digests are nonce-bound',()=>{const s=secret();assert.equal(s.length,43);assert.equal(validSecret(s),true);assert.equal(validSecret(hash(s)),false);assert.equal(validSecret(s+'='),false);assert.equal(sameHash(hash(s),hash(s)),true);assert.equal(sameHash('a','b'),false);assert.notEqual(codeDigest(s,'12345678'),codeDigest(secret(),'12345678'));});
test('session cookies are host-only, secure and inaccessible to scripts',()=>{const s=secret(),c=setCookie(COOKIE,s,600);for(const f of ['__Host-','Secure','HttpOnly','SameSite=Strict','Path=/'])assert.ok(c.includes(f));assert.ok(!c.includes('Domain='));assert.equal(cookieValue(COOKIE+'='+s,COOKIE),s);assert.equal(cookieValue(COOKIE+'='+s+'; '+COOKIE+'='+s,COOKIE),null);});
test('email configuration is separate from billing and requires a branded sender',()=>{assert.equal(webConfig({}).emailReady,false);assert.equal(config.emailReady,true);assert.equal(webConfig({RESEND_API_KEY:'re_'+'x'.repeat(24),AUTH_EMAIL_FROM:'Acme <attacker@example.com>'}).emailReady,false);assert.throws(()=>webConfig({AUTH_ORIGIN:'http://example.com'}));});
test('cookie-authenticated writes require exact Origin plus a custom request header',()=>{assert.doesNotThrow(()=>requireOrigin({headers:{origin:config.origin,'x-chatdrobe-request':'account-v1'}},config));for(const headers of [{origin:'https://evil.example','x-chatdrobe-request':'account-v1'},{origin:config.origin},{origin:config.origin,'x-chatdrobe-request':'account-v1','sec-fetch-site':'cross-site'}])assert.throws(()=>requireOrigin({headers},config));});
test('admin authority is a verified server role and activation requires recent auth',()=>{assert.throws(()=>requireAdmin({email:'owner@example.com',role:'user',verifiedAt:'2026-01-01'}),{code:'FORBIDDEN'});const u={role:'admin',verifiedAt:'2026-01-01',authenticatedAt:1000};assert.doesNotThrow(()=>requireAdmin(u,{fresh:true,now:1500}));assert.throws(()=>requireAdmin(u,{fresh:true,now:2000}),{code:'REAUTHENTICATE'});assert.throws(()=>requireAdmin({...u,disabledAt:'today'}),{code:'FORBIDDEN'});assert.throws(()=>requireAdmin({...u,authenticatedAt:undefined},{fresh:true,now:1500}));});
test('test subscriptions are distinct from live users; stale and held subscriptions are Free',()=>{assert.equal(subscriptionSummary({status:'active',paidUntil:2000},1000).plan,'test_plus');for(const s of [{},{status:'active',paidUntil:1000},{status:'active',paidUntil:2000,hold:'refund'},{status:'past_due',paidUntil:2000}])assert.equal(subscriptionSummary(s,1000).plan,'free');});
test('mailer uses one recipient/idempotency and never returns the code or provider errors',async()=>{let seen;const mail=codeMailer(config,async(url,opts)=>{seen={url,opts};return new Response('{"id":"message"}',{status:200});});assert.deepEqual(await mail({email:'user@example.com',code:'12345678',requestId:'request'}),{sent:true});const body=JSON.parse(seen.opts.body);assert.deepEqual(body.to,['user@example.com']);assert.ok(body.text.includes('12345678'));assert.equal(seen.opts.redirect,'error');assert.equal(seen.opts.headers['Idempotency-Key'],'chatdrobe-login/request');const fail=codeMailer(config,async()=>new Response('secret provider error',{status:403}));await assert.rejects(fail({email:'u@example.com',code:'12345678',requestId:'r'}),e=>e.code==='EMAIL_UNAVAILABLE'&&!e.message.includes('secret'));});
test('code requests expose no code or account; delivery failure invalidates the challenge',async()=>{let recorded,sent,invalidated;const accounts={challenge:async v=>{recorded=v;},invalidate:async v=>{invalidated=v;}},limitCalls=[],billingStore={limit:async(...a)=>limitCalls.push(a)};const s=accountService({accounts,billingStore,config,mailer:async v=>{sent=v;},payments:{},now:()=>1000});const r=await s.requestCode({email:'U@example.com',mode:'signup',acceptBeta:true},{ip:'test'});assert.equal(recorded.email,'u@example.com');assert.equal(recorded.nonceHash,hash(r.nonce));assert.equal(recorded.codeHash,codeDigest(r.nonce,sent.code));assert.equal(recorded.expiresAt,1600);assert.equal(limitCalls.length,3);assert.ok(!JSON.stringify(r.public).includes(sent.code));const fail=accountService({accounts,billingStore,config,mailer:async()=>{throw new AccountError('EMAIL_UNAVAILABLE','Unavailable',503);},payments:{}});await assert.rejects(fail.requestCode({email:'u@example.com',mode:'signin'}));assert.equal(invalidated,recorded.nonceHash);});
async function app(t){let calls=0;const service={authenticate:async token=>{if(!token)throw new AccountError('SIGN_IN_REQUIRED','Sign in.',401);return {id:'u',role:'user',verifiedAt:'yes'};},requestCode:async()=>{calls++;return {nonce:secret(),public:{ok:true,message:'Check email.'}};},verifyCode:async()=>({token:secret(),seconds:600,user:{email:'user@example.com',role:'user'}}),admin:async user=>{requireAdmin(user);return {users:[]};},setup:async user=>{requireAdmin(user);return {};},profile:async()=>({user:{email:'user@example.com'}}),signout:async()=>({ok:true}),signoutAll:async()=>({ok:true})};const server=http.createServer(createAccountHandler(async()=>({service}),{config:()=>config}));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port+'/api/account',post=(action,input={},headers={})=>fetch(base+'?action='+action,{method:'POST',headers:{origin:config.origin,'x-chatdrobe-request':'account-v1','content-type':'application/json',...headers},body:JSON.stringify(input)});return {base,post,calls:()=>calls};}
test('HTTP rejects role injection, CSRF, oversized bodies and wrong methods before mail',async t=>{const a=await app(t);assert.equal((await a.post('request-code',{email:'u@example.com',mode:'signup',role:'admin'})).status,400);assert.equal((await a.post('request-code',{}, {origin:'https://evil.example'})).status,403);assert.equal((await a.post('request-code',{email:'x'.repeat(3000)})).status,413);assert.equal((await fetch(a.base+'?action=request-code')).status,405);assert.equal(a.calls(),0);});
test('HTTP credentials are only in protected cookies, not JSON',async t=>{const a=await app(t),r=await a.post('request-code',{email:'u@example.com',mode:'signin'});assert.equal(r.status,202);const c=r.headers.getSetCookie()[0];assert.ok(c.startsWith(CHALLENGE_COOKIE+'='));assert.ok(c.includes('HttpOnly'));assert.deepEqual(await r.json(),{ok:true,message:'Check email.'});const v=await a.post('verify-code',{code:'12345678'},{cookie:c.split(';')[0]});assert.equal(v.status,200);assert.equal(v.headers.getSetCookie().length,2);const data=await v.json();assert.deepEqual(Object.keys(data),['user']);assert.ok(!JSON.stringify(data).includes('token'));});
test('HTTP admin rejects anonymous and ordinary sessions and forbids caching',async t=>{const a=await app(t);assert.equal((await a.post('admin-users',{})).status,401);const r=await a.post('admin-users',{}, {cookie:COOKIE+'='+secret()});assert.equal(r.status,403);assert.match(r.headers.get('cache-control'),/no-store/);assert.equal(r.headers.get('access-control-allow-origin'),null);assert.equal((await fetch(a.base+'?action=admin-setup',{headers:{cookie:COOKIE+'='+secret()}})).status,403);});
