import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync} from 'node:crypto';
import {membership,accessSigningConfiguration,adminDeviceLease,REMEMBER_SECONDS} from '../premium-membership.mjs';
import {SESSION_SECONDS,ADMIN_SESSION_SECONDS,requireAdmin} from '../accounts-policy.mjs';
import {bindDeviceLease} from '../device-lease.mjs';
import verifier from '../../contracts/extension-entitlement.cjs';
const now=1700000000,id='a'.repeat(64),account='b'.repeat(64);
function config(){const {privateKey}=generateKeyPairSync('ec',{namedCurve:'prime256v1'});return accessSigningConfiguration({BILLING_SIGNING_PRIVATE_KEY:privateKey.export({type:'pkcs8',format:'pem'})});}
const device=()=>({role:'admin',billing_id:account,expires_at:new Date((now+30*86400)*1000),disabled_at:null,revoked_at:null});
test('current admin receives complimentary Premium without changing their subscription record',()=>{const record={plan:'free',status:'free'};assert.deepEqual(membership({role:'admin'},record),{premium:true,complimentary:true,source:'admin',label:'Admin Premium — complimentary'});assert.equal(record.plan,'free');assert.equal(membership({role:'user'},record).premium,false);assert.equal(membership({role:'admin',disabledAt:'disabled'},record).premium,false);});
test('subscriptions remain separate from administrative grants',()=>{assert.equal(membership({role:'user'},{plan:'test_plus'}).source,'stripe_test');assert.equal(membership({role:'admin'},{plan:'test_plus'}).source,'admin');assert.equal(membership({email:'owner@example.com'},{plan:'free'}).premium,false);});
test('admin proof is genuinely signed, account/device-bound and not labeled a test purchase',async()=>{const cfg=config(),proof=adminDeviceLease(cfg,device(),id,now),result=await verifier.verify(proof.token,{...cfg,deviceId:id,now});assert.equal(result.premium,true);assert.equal(result.adminPremium,true);assert.equal(result.testSubscription,false);assert.equal(result.paid,false);assert.equal(result.subject,account);assert.equal(result.expiresAt,now+600);await assert.rejects(verifier.verify(proof.token,{...cfg,deviceId:'c'.repeat(64),now}));});
test('administrator access works with Stripe off, but not without a valid signing key',()=>{const {privateKey}=generateKeyPairSync('ec',{namedCurve:'prime256v1'});const cfg=accessSigningConfiguration({BILLING_MODE:'off',BILLING_SIGNING_PRIVATE_KEY:privateKey.export({type:'pkcs8',format:'pem'})});assert.equal(adminDeviceLease(cfg,device(),id,now).accessSource,'admin');assert.throws(()=>accessSigningConfiguration({}),{code:'ACCESS_SIGNING_NOT_READY'});});
test('demoted, disabled, expired or revoked devices cannot mint an admin proof',()=>{const cfg=config();for(const change of [{role:'user'},{disabled_at:'disabled'},{revoked_at:'revoked'},{expires_at:new Date(now*1000)},{billing_id:'invalid'}])assert.throws(()=>adminDeviceLease(cfg,{...device(),...change},id,now),{code:'ACCESS_DENIED'});});
test('device expiration caps a grant even within the ten-minute entitlement window',async()=>{const cfg=config(),proof=adminDeviceLease(cfg,{...device(),expires_at:new Date((now+60)*1000)},id,now);assert.equal(proof.expiresAt,now+60);await assert.rejects(verifier.verify(proof.token,{...cfg,deviceId:id,now:now+60}));});
test('remembered sessions last thirty days but do not keep administrative operations fresh',()=>{assert.equal(SESSION_SECONDS,30*86400);assert.equal(ADMIN_SESSION_SECONDS,REMEMBER_SECONDS);assert.throws(()=>requireAdmin({role:'admin',verifiedAt:'verified',authenticatedAt:now-901},{fresh:true,now}),{code:'REAUTHENTICATE'});assert.doesNotThrow(()=>requireAdmin({role:'admin',verifiedAt:'verified',authenticatedAt:now-300},{fresh:true,now}));});
test('billing binding rejects a complimentary proof rather than relabeling it a payment',()=>{const cfg=config(),proof=adminDeviceLease(cfg,device(),id,now);assert.throws(()=>bindDeviceLease(cfg,proof,id,new Date((now+50)*1000)),/Unexpected internal/);});
